INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('grdetkwyei', '98565028', 'DIR', 'HR', 'GLOBAL');
INSERT INTO salary (salary) VALUES (84000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('ebcquwgncx', '98846795', 'DIR', 'HR', 'APAC');
INSERT INTO salary (salary) VALUES (37000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('rvbkwrkjzg', '97060727', 'DIR', 'HR', 'SG');
INSERT INTO salary (salary) VALUES (64000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('bwkkmgxkth', '91830940', 'DIR', 'HR', 'HK');
INSERT INTO salary (salary) VALUES (89000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('tiycpafgpq', '93894677', 'DIR', 'HR', 'EMEA');
INSERT INTO salary (salary) VALUES (100000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('vgwacjftko', '91625471', 'DIR', 'HR', 'LON');
INSERT INTO salary (salary) VALUES (83000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('ikztdcuqlj', '96230203', 'DIR', 'HR', 'PAR');
INSERT INTO salary (salary) VALUES (58000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('aravynojfd', '92531547', 'DIR', 'HR', 'AMER');
INSERT INTO salary (salary) VALUES (95000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('rmtdhtarwt', '92808936', 'DIR', 'HR', 'NY');
INSERT INTO salary (salary) VALUES (86000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('oourfpvcbm', '99558979', 'DIR', 'HR', 'SF');
INSERT INTO salary (salary) VALUES (32000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('oonckvfvfc', '92038641', 'MGR', 'HR', 'GLOBAL');
INSERT INTO salary (salary) VALUES (59000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('akzjxsmppd', '95656167', 'MGR', 'HR', 'APAC');
INSERT INTO salary (salary) VALUES (70000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('dkgtezaqzr', '98940662', 'MGR', 'HR', 'SG');
INSERT INTO salary (salary) VALUES (93000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('datdizlwnt', '95357753', 'MGR', 'HR', 'HK');
INSERT INTO salary (salary) VALUES (49000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('auqbaoqrua', '90376867', 'MGR', 'HR', 'EMEA');
INSERT INTO salary (salary) VALUES (31000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('ikkamalylt', '91402384', 'MGR', 'HR', 'LON');
INSERT INTO salary (salary) VALUES (67000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('wdcxrlqkvu', '93354042', 'MGR', 'HR', 'PAR');
INSERT INTO salary (salary) VALUES (36000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('jhfsysmphl', '94427094', 'MGR', 'HR', 'AMER');
INSERT INTO salary (salary) VALUES (49000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('slgbrfqtir', '97558872', 'MGR', 'HR', 'NY');
INSERT INTO salary (salary) VALUES (72000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('waawdrbtjl', '95191380', 'MGR', 'HR', 'SF');
INSERT INTO salary (salary) VALUES (74000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('yversnkerw', '98532958', 'EMP', 'HR', 'GLOBAL');
INSERT INTO salary (salary) VALUES (81000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('tcxvkmhenu', '93207947', 'EMP', 'HR', 'APAC');
INSERT INTO salary (salary) VALUES (44000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('mnzyiyhzff', '99020992', 'EMP', 'HR', 'SG');
INSERT INTO salary (salary) VALUES (67000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('tejnvilpax', '94034307', 'EMP', 'HR', 'HK');
INSERT INTO salary (salary) VALUES (89000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('iuwncrparf', '98867317', 'EMP', 'HR', 'EMEA');
INSERT INTO salary (salary) VALUES (85000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('jipuborijf', '93991624', 'EMP', 'HR', 'LON');
INSERT INTO salary (salary) VALUES (32000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('zkvqtdgexe', '95375614', 'EMP', 'HR', 'PAR');
INSERT INTO salary (salary) VALUES (57000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('wbbzznrzik', '93097766', 'EMP', 'HR', 'AMER');
INSERT INTO salary (salary) VALUES (54000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('xbmbxjrgbn', '99973198', 'EMP', 'HR', 'NY');
INSERT INTO salary (salary) VALUES (38000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('buapktjygq', '94146998', 'EMP', 'HR', 'SF');
INSERT INTO salary (salary) VALUES (86000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('arpbbcsygk', '92367771', 'DIR', 'FIN', 'GLOBAL');
INSERT INTO salary (salary) VALUES (33000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('hazsuzxkzj', '91757730', 'DIR', 'FIN', 'APAC');
INSERT INTO salary (salary) VALUES (53000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('jauvklouji', '98884086', 'DIR', 'FIN', 'SG');
INSERT INTO salary (salary) VALUES (60000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('dsksxmwlob', '90028498', 'DIR', 'FIN', 'HK');
INSERT INTO salary (salary) VALUES (56000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('qrkeurodll', '90994552', 'DIR', 'FIN', 'EMEA');
INSERT INTO salary (salary) VALUES (91000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('jhgdtqlsht', '91322511', 'DIR', 'FIN', 'LON');
INSERT INTO salary (salary) VALUES (84000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('cdtuqjyxtr', '90300444', 'DIR', 'FIN', 'PAR');
INSERT INTO salary (salary) VALUES (46000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('qpatsgqxvw', '90841661', 'DIR', 'FIN', 'AMER');
INSERT INTO salary (salary) VALUES (95000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('tgbdrfgenl', '93863783', 'DIR', 'FIN', 'NY');
INSERT INTO salary (salary) VALUES (81000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('qpmkdggpfs', '96299151', 'DIR', 'FIN', 'SF');
INSERT INTO salary (salary) VALUES (40000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('pvqanvhvfd', '91539189', 'MGR', 'FIN', 'GLOBAL');
INSERT INTO salary (salary) VALUES (40000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('shtkbpdirx', '98168851', 'MGR', 'FIN', 'APAC');
INSERT INTO salary (salary) VALUES (99000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('zbehfjenys', '96037941', 'MGR', 'FIN', 'SG');
INSERT INTO salary (salary) VALUES (46000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('ivwvedewzo', '96765167', 'MGR', 'FIN', 'HK');
INSERT INTO salary (salary) VALUES (75000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('lfggxfnwbw', '99734530', 'MGR', 'FIN', 'EMEA');
INSERT INTO salary (salary) VALUES (42000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('jgyhnalfet', '92811454', 'MGR', 'FIN', 'LON');
INSERT INTO salary (salary) VALUES (33000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('mjzhssswko', '95620099', 'MGR', 'FIN', 'PAR');
INSERT INTO salary (salary) VALUES (68000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('fnlfbvpqha', '92545192', 'MGR', 'FIN', 'AMER');
INSERT INTO salary (salary) VALUES (89000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('fmrcwtkuap', '93561988', 'MGR', 'FIN', 'NY');
INSERT INTO salary (salary) VALUES (31000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('bxnwsxcobf', '97657133', 'MGR', 'FIN', 'SF');
INSERT INTO salary (salary) VALUES (62000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('vmffofzahc', '99496335', 'EMP', 'FIN', 'GLOBAL');
INSERT INTO salary (salary) VALUES (37000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('jjaztgljoc', '93802732', 'EMP', 'FIN', 'APAC');
INSERT INTO salary (salary) VALUES (82000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('jxiamzpwnx', '94166332', 'EMP', 'FIN', 'SG');
INSERT INTO salary (salary) VALUES (71000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('lldipvwfxk', '96521381', 'EMP', 'FIN', 'HK');
INSERT INTO salary (salary) VALUES (34000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('ysxgrxkonx', '99787272', 'EMP', 'FIN', 'EMEA');
INSERT INTO salary (salary) VALUES (50000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('svvnuwtizu', '90767932', 'EMP', 'FIN', 'LON');
INSERT INTO salary (salary) VALUES (81000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('qehvavnnbn', '99013014', 'EMP', 'FIN', 'PAR');
INSERT INTO salary (salary) VALUES (86000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('uiuzkobqvk', '98758524', 'EMP', 'FIN', 'AMER');
INSERT INTO salary (salary) VALUES (96000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('mwlpdzlztb', '92020286', 'EMP', 'FIN', 'NY');
INSERT INTO salary (salary) VALUES (58000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('bhaucpnwqr', '90237791', 'EMP', 'FIN', 'SF');
INSERT INTO salary (salary) VALUES (62000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('wuzhaupvsn', '92510261', 'DIR', 'ENG', 'GLOBAL');
INSERT INTO salary (salary) VALUES (91000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('mcqihvqkzf', '94440594', 'DIR', 'ENG', 'APAC');
INSERT INTO salary (salary) VALUES (60000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('nigceawgjv', '94068013', 'DIR', 'ENG', 'SG');
INSERT INTO salary (salary) VALUES (64000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('huqfgnoncx', '90775484', 'DIR', 'ENG', 'HK');
INSERT INTO salary (salary) VALUES (34000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('akbeiikevy', '97570600', 'DIR', 'ENG', 'EMEA');
INSERT INTO salary (salary) VALUES (76000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('abzxeqagjv', '97750589', 'DIR', 'ENG', 'LON');
INSERT INTO salary (salary) VALUES (41000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('rebqdgorug', '96299623', 'DIR', 'ENG', 'PAR');
INSERT INTO salary (salary) VALUES (58000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('gfxubqifdt', '98919021', 'DIR', 'ENG', 'AMER');
INSERT INTO salary (salary) VALUES (35000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('jfthptvmdf', '96434552', 'DIR', 'ENG', 'NY');
INSERT INTO salary (salary) VALUES (100000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('zqmhbqgcor', '91142007', 'DIR', 'ENG', 'SF');
INSERT INTO salary (salary) VALUES (35000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('dlwshrcjnk', '96052079', 'MGR', 'ENG', 'GLOBAL');
INSERT INTO salary (salary) VALUES (31000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('qmrllrprjd', '96402696', 'MGR', 'ENG', 'APAC');
INSERT INTO salary (salary) VALUES (52000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('femoxuckrl', '98430761', 'MGR', 'ENG', 'SG');
INSERT INTO salary (salary) VALUES (50000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('eatxrjxsph', '95817465', 'MGR', 'ENG', 'HK');
INSERT INTO salary (salary) VALUES (71000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('gfjjchfcsu', '93795105', 'MGR', 'ENG', 'EMEA');
INSERT INTO salary (salary) VALUES (70000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('dkcoyvpcrf', '90806636', 'MGR', 'ENG', 'LON');
INSERT INTO salary (salary) VALUES (55000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('ioguutoyqu', '90738197', 'MGR', 'ENG', 'PAR');
INSERT INTO salary (salary) VALUES (36000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('tuhrlvilvy', '93958919', 'MGR', 'ENG', 'AMER');
INSERT INTO salary (salary) VALUES (65000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('vjpokmdntr', '95258066', 'MGR', 'ENG', 'NY');
INSERT INTO salary (salary) VALUES (53000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('btmgernekd', '95749486', 'MGR', 'ENG', 'SF');
INSERT INTO salary (salary) VALUES (32000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('fxprfvarci', '92817668', 'EMP', 'ENG', 'GLOBAL');
INSERT INTO salary (salary) VALUES (45000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('ughnmacapv', '93392693', 'EMP', 'ENG', 'APAC');
INSERT INTO salary (salary) VALUES (52000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('dmjcbdqgce', '92732808', 'EMP', 'ENG', 'SG');
INSERT INTO salary (salary) VALUES (58000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('dqqcnivzqr', '96986703', 'EMP', 'ENG', 'HK');
INSERT INTO salary (salary) VALUES (38000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('zqgldhlnea', '98443444', 'EMP', 'ENG', 'EMEA');
INSERT INTO salary (salary) VALUES (64000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('nwusojuswd', '99368664', 'EMP', 'ENG', 'LON');
INSERT INTO salary (salary) VALUES (97000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('kjsoraoygx', '98226741', 'EMP', 'ENG', 'PAR');
INSERT INTO salary (salary) VALUES (45000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('aqxpxhojot', '90075517', 'EMP', 'ENG', 'AMER');
INSERT INTO salary (salary) VALUES (71000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('iqwslxjddc', '94874796', 'EMP', 'ENG', 'NY');
INSERT INTO salary (salary) VALUES (50000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('pgvhvfqpcf', '98634639', 'EMP', 'ENG', 'SF');
INSERT INTO salary (salary) VALUES (33000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('kdftmfucka', '99656557', 'DIR', 'HR', 'GLOBAL');
INSERT INTO salary (salary) VALUES (88000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('ybdawdfuic', '93568172', 'DIR', 'HR', 'APAC');
INSERT INTO salary (salary) VALUES (83000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('pxltuiuyys', '97573687', 'DIR', 'HR', 'SG');
INSERT INTO salary (salary) VALUES (93000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('pjzxewvgqs', '93045698', 'DIR', 'HR', 'HK');
INSERT INTO salary (salary) VALUES (45000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('nahyjdnboq', '99240269', 'DIR', 'HR', 'EMEA');
INSERT INTO salary (salary) VALUES (38000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('kskwnmpguw', '95118275', 'DIR', 'HR', 'LON');
INSERT INTO salary (salary) VALUES (54000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('tbmlmljzxt', '94387123', 'DIR', 'HR', 'PAR');
INSERT INTO salary (salary) VALUES (32000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('qpjxiakwca', '95769582', 'DIR', 'HR', 'AMER');
INSERT INTO salary (salary) VALUES (63000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('dhtuxalitx', '90605764', 'DIR', 'HR', 'NY');
INSERT INTO salary (salary) VALUES (63000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('bjwrcfrpyz', '91638723', 'DIR', 'HR', 'SF');
INSERT INTO salary (salary) VALUES (87000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('gfehpitfjf', '93853103', 'MGR', 'HR', 'GLOBAL');
INSERT INTO salary (salary) VALUES (52000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('cyvylvbeds', '96908142', 'MGR', 'HR', 'APAC');
INSERT INTO salary (salary) VALUES (80000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('kqgzdtjymv', '98787274', 'MGR', 'HR', 'SG');
INSERT INTO salary (salary) VALUES (43000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('mlvckelaec', '98370248', 'MGR', 'HR', 'HK');
INSERT INTO salary (salary) VALUES (84000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('dtojevgrfr', '96578108', 'MGR', 'HR', 'EMEA');
INSERT INTO salary (salary) VALUES (94000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('brweevsqdd', '96380667', 'MGR', 'HR', 'LON');
INSERT INTO salary (salary) VALUES (78000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('mqnlwybbzd', '99082201', 'MGR', 'HR', 'PAR');
INSERT INTO salary (salary) VALUES (38000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('huhybuwnix', '93181347', 'MGR', 'HR', 'AMER');
INSERT INTO salary (salary) VALUES (63000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('hbaizcbxvg', '99182809', 'MGR', 'HR', 'NY');
INSERT INTO salary (salary) VALUES (72000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('exxncywvde', '92841838', 'MGR', 'HR', 'SF');
INSERT INTO salary (salary) VALUES (92000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('dskdpuevqk', '95814327', 'EMP', 'HR', 'GLOBAL');
INSERT INTO salary (salary) VALUES (64000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('iahzctkgjg', '95676693', 'EMP', 'HR', 'APAC');
INSERT INTO salary (salary) VALUES (66000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('ogozlzlthw', '90129724', 'EMP', 'HR', 'SG');
INSERT INTO salary (salary) VALUES (96000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('eddawnmobp', '90105579', 'EMP', 'HR', 'HK');
INSERT INTO salary (salary) VALUES (58000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('vuujiguwkq', '98352868', 'EMP', 'HR', 'EMEA');
INSERT INTO salary (salary) VALUES (48000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('wptiwosyoh', '94095754', 'EMP', 'HR', 'LON');
INSERT INTO salary (salary) VALUES (84000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('eywsafagcr', '93503961', 'EMP', 'HR', 'PAR');
INSERT INTO salary (salary) VALUES (61000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('qkmtvscrwm', '92897009', 'EMP', 'HR', 'AMER');
INSERT INTO salary (salary) VALUES (35000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('bnixrxetrs', '94275058', 'EMP', 'HR', 'NY');
INSERT INTO salary (salary) VALUES (40000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('vwofwbfwde', '99167025', 'EMP', 'HR', 'SF');
INSERT INTO salary (salary) VALUES (68000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('wvtpzgtbgh', '93738195', 'DIR', 'FIN', 'GLOBAL');
INSERT INTO salary (salary) VALUES (99000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('ryhuscxxuf', '98207418', 'DIR', 'FIN', 'APAC');
INSERT INTO salary (salary) VALUES (81000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('ovmaismwsi', '99645130', 'DIR', 'FIN', 'SG');
INSERT INTO salary (salary) VALUES (74000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('yqgorvrklb', '97977365', 'DIR', 'FIN', 'HK');
INSERT INTO salary (salary) VALUES (64000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('vqobxuxfde', '98457685', 'DIR', 'FIN', 'EMEA');
INSERT INTO salary (salary) VALUES (47000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('hwlclkagyv', '99104840', 'DIR', 'FIN', 'LON');
INSERT INTO salary (salary) VALUES (85000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('qxtzocsvkg', '98927110', 'DIR', 'FIN', 'PAR');
INSERT INTO salary (salary) VALUES (31000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('bbumqhwnne', '92077558', 'DIR', 'FIN', 'AMER');
INSERT INTO salary (salary) VALUES (59000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('hpxxqdghdc', '93293929', 'DIR', 'FIN', 'NY');
INSERT INTO salary (salary) VALUES (83000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('paukbtgmgu', '96786299', 'DIR', 'FIN', 'SF');
INSERT INTO salary (salary) VALUES (51000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('pefrpawkdo', '91210605', 'MGR', 'FIN', 'GLOBAL');
INSERT INTO salary (salary) VALUES (72000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('zuubdxvdvn', '96711225', 'MGR', 'FIN', 'APAC');
INSERT INTO salary (salary) VALUES (76000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('abefyqdxvy', '93198851', 'MGR', 'FIN', 'SG');
INSERT INTO salary (salary) VALUES (52000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('zuoduppnqb', '96053922', 'MGR', 'FIN', 'HK');
INSERT INTO salary (salary) VALUES (37000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('rvxsemufgd', '90780929', 'MGR', 'FIN', 'EMEA');
INSERT INTO salary (salary) VALUES (80000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('xcbirwqytw', '91757331', 'MGR', 'FIN', 'LON');
INSERT INTO salary (salary) VALUES (91000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('pgwahehprj', '99378471', 'MGR', 'FIN', 'PAR');
INSERT INTO salary (salary) VALUES (44000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('fdctskosvz', '99342014', 'MGR', 'FIN', 'AMER');
INSERT INTO salary (salary) VALUES (43000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('igqirjwipn', '90527263', 'MGR', 'FIN', 'NY');
INSERT INTO salary (salary) VALUES (83000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('ezpefxebjn', '90386397', 'MGR', 'FIN', 'SF');
INSERT INTO salary (salary) VALUES (68000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('ajaugdifgx', '97306672', 'EMP', 'FIN', 'GLOBAL');
INSERT INTO salary (salary) VALUES (61000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('pwfnqfcujc', '99376239', 'EMP', 'FIN', 'APAC');
INSERT INTO salary (salary) VALUES (97000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('qvrtkolkjq', '95029302', 'EMP', 'FIN', 'SG');
INSERT INTO salary (salary) VALUES (57000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('bfjtddolyj', '93874313', 'EMP', 'FIN', 'HK');
INSERT INTO salary (salary) VALUES (97000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('firymjqejh', '91318761', 'EMP', 'FIN', 'EMEA');
INSERT INTO salary (salary) VALUES (74000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('xwjpgpggeo', '98523573', 'EMP', 'FIN', 'LON');
INSERT INTO salary (salary) VALUES (31000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('fztjmhhtsc', '92458980', 'EMP', 'FIN', 'PAR');
INSERT INTO salary (salary) VALUES (74000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('tuagsjortm', '99989527', 'EMP', 'FIN', 'AMER');
INSERT INTO salary (salary) VALUES (72000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('iqcothzexd', '97466666', 'EMP', 'FIN', 'NY');
INSERT INTO salary (salary) VALUES (52000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('urtrklhlie', '95848382', 'EMP', 'FIN', 'SF');
INSERT INTO salary (salary) VALUES (39000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('dcpcaqlsmo', '98731160', 'DIR', 'ENG', 'GLOBAL');
INSERT INTO salary (salary) VALUES (70000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('kydfsgsodb', '96637036', 'DIR', 'ENG', 'APAC');
INSERT INTO salary (salary) VALUES (48000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('vcrdjpbava', '95391825', 'DIR', 'ENG', 'SG');
INSERT INTO salary (salary) VALUES (83000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('vqkiujuysf', '93196415', 'DIR', 'ENG', 'HK');
INSERT INTO salary (salary) VALUES (78000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('pdxgphtryu', '91696631', 'DIR', 'ENG', 'EMEA');
INSERT INTO salary (salary) VALUES (56000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('pulxgtsurw', '93733675', 'DIR', 'ENG', 'LON');
INSERT INTO salary (salary) VALUES (42000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('ruirmitcdc', '94949637', 'DIR', 'ENG', 'PAR');
INSERT INTO salary (salary) VALUES (73000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('txfyvhtrmb', '96145183', 'DIR', 'ENG', 'AMER');
INSERT INTO salary (salary) VALUES (68000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('nujveoufdm', '91458065', 'DIR', 'ENG', 'NY');
INSERT INTO salary (salary) VALUES (93000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('ismakpjeka', '99955589', 'DIR', 'ENG', 'SF');
INSERT INTO salary (salary) VALUES (35000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('gfslfmfqhw', '93271599', 'MGR', 'ENG', 'GLOBAL');
INSERT INTO salary (salary) VALUES (32000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('hynmfpektk', '98522163', 'MGR', 'ENG', 'APAC');
INSERT INTO salary (salary) VALUES (82000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('qjvwwvpora', '92515734', 'MGR', 'ENG', 'SG');
INSERT INTO salary (salary) VALUES (50000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('vpamwxmqmr', '91150250', 'MGR', 'ENG', 'HK');
INSERT INTO salary (salary) VALUES (76000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('jzqztnhasp', '97591566', 'MGR', 'ENG', 'EMEA');
INSERT INTO salary (salary) VALUES (63000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('ovcldkrnxc', '94050844', 'MGR', 'ENG', 'LON');
INSERT INTO salary (salary) VALUES (79000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('ruadirrkbn', '91526088', 'MGR', 'ENG', 'PAR');
INSERT INTO salary (salary) VALUES (35000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('bzhgcnxeel', '94818663', 'MGR', 'ENG', 'AMER');
INSERT INTO salary (salary) VALUES (46000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('gfuvzbnshy', '92497973', 'MGR', 'ENG', 'NY');
INSERT INTO salary (salary) VALUES (73000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('efdalbuapa', '99162311', 'MGR', 'ENG', 'SF');
INSERT INTO salary (salary) VALUES (42000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('sxptsmrbsy', '92405096', 'EMP', 'ENG', 'GLOBAL');
INSERT INTO salary (salary) VALUES (52000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('exvhzabolw', '96862122', 'EMP', 'ENG', 'APAC');
INSERT INTO salary (salary) VALUES (92000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('pxdauhxvyi', '94844767', 'EMP', 'ENG', 'SG');
INSERT INTO salary (salary) VALUES (94000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('cxajprnalc', '94340362', 'EMP', 'ENG', 'HK');
INSERT INTO salary (salary) VALUES (44000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('dwucfkmpmv', '98481335', 'EMP', 'ENG', 'EMEA');
INSERT INTO salary (salary) VALUES (58000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('tntagivnjl', '90797011', 'EMP', 'ENG', 'LON');
INSERT INTO salary (salary) VALUES (47000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('exedxjwqoj', '94736435', 'EMP', 'ENG', 'PAR');
INSERT INTO salary (salary) VALUES (45000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('ndtzniqocr', '95695298', 'EMP', 'ENG', 'AMER');
INSERT INTO salary (salary) VALUES (71000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('auvoecphbu', '94813914', 'EMP', 'ENG', 'NY');
INSERT INTO salary (salary) VALUES (80000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('rcxkrtmjuc', '92569043', 'EMP', 'ENG', 'SF');
INSERT INTO salary (salary) VALUES (34000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('gsaniulakt', '94068467', 'DIR', 'HR', 'GLOBAL');
INSERT INTO salary (salary) VALUES (95000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('hqkdpsszec', '99403480', 'DIR', 'HR', 'APAC');
INSERT INTO salary (salary) VALUES (95000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('adyidxvqzt', '99595176', 'DIR', 'HR', 'SG');
INSERT INTO salary (salary) VALUES (35000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('qmpgtepyvr', '96767429', 'DIR', 'HR', 'HK');
INSERT INTO salary (salary) VALUES (84000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('njqgnhujrc', '95142747', 'DIR', 'HR', 'EMEA');
INSERT INTO salary (salary) VALUES (82000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('gnxnxuefig', '95933896', 'DIR', 'HR', 'LON');
INSERT INTO salary (salary) VALUES (98000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('opcpuudtoz', '90467726', 'DIR', 'HR', 'PAR');
INSERT INTO salary (salary) VALUES (36000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('tybywljcqe', '96253754', 'DIR', 'HR', 'AMER');
INSERT INTO salary (salary) VALUES (39000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('kjqmuxixly', '94469145', 'DIR', 'HR', 'NY');
INSERT INTO salary (salary) VALUES (37000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('svgupndtsu', '92361413', 'DIR', 'HR', 'SF');
INSERT INTO salary (salary) VALUES (96000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('dwyzwahgme', '95862198', 'MGR', 'HR', 'GLOBAL');
INSERT INTO salary (salary) VALUES (83000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('dvrsapsfcv', '98381671', 'MGR', 'HR', 'APAC');
INSERT INTO salary (salary) VALUES (90000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('wtvbfkzwvu', '97961389', 'MGR', 'HR', 'SG');
INSERT INTO salary (salary) VALUES (64000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('zzgenlbmyq', '95803784', 'MGR', 'HR', 'HK');
INSERT INTO salary (salary) VALUES (45000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('wuegiklofv', '98404214', 'MGR', 'HR', 'EMEA');
INSERT INTO salary (salary) VALUES (96000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('bthnccpill', '97151923', 'MGR', 'HR', 'LON');
INSERT INTO salary (salary) VALUES (55000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('ugsskaavgw', '98165978', 'MGR', 'HR', 'PAR');
INSERT INTO salary (salary) VALUES (52000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('vrbzbsxcfk', '95942063', 'MGR', 'HR', 'AMER');
INSERT INTO salary (salary) VALUES (84000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('bseordkcbn', '90221463', 'MGR', 'HR', 'NY');
INSERT INTO salary (salary) VALUES (32000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('hkvhwpllpe', '90922301', 'MGR', 'HR', 'SF');
INSERT INTO salary (salary) VALUES (73000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('lugmvfqxig', '93303739', 'EMP', 'HR', 'GLOBAL');
INSERT INTO salary (salary) VALUES (79000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('fmmegpxhdy', '91344875', 'EMP', 'HR', 'APAC');
INSERT INTO salary (salary) VALUES (64000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('uyqhrlcwgn', '93494272', 'EMP', 'HR', 'SG');
INSERT INTO salary (salary) VALUES (43000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('wykevhbrgo', '98319388', 'EMP', 'HR', 'HK');
INSERT INTO salary (salary) VALUES (68000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('naybkroqms', '90977237', 'EMP', 'HR', 'EMEA');
INSERT INTO salary (salary) VALUES (52000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('jiejrvgyth', '98634585', 'EMP', 'HR', 'LON');
INSERT INTO salary (salary) VALUES (86000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('mvywkpeype', '91655817', 'EMP', 'HR', 'PAR');
INSERT INTO salary (salary) VALUES (81000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('vpetpmcydi', '92420794', 'EMP', 'HR', 'AMER');
INSERT INTO salary (salary) VALUES (83000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('ndrchdwucl', '92893067', 'EMP', 'HR', 'NY');
INSERT INTO salary (salary) VALUES (38000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('maefnlswqu', '95179347', 'EMP', 'HR', 'SF');
INSERT INTO salary (salary) VALUES (33000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('jnvsxcownp', '94502325', 'DIR', 'FIN', 'GLOBAL');
INSERT INTO salary (salary) VALUES (80000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('ssuihzrlgm', '90646461', 'DIR', 'FIN', 'APAC');
INSERT INTO salary (salary) VALUES (99000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('acqhwhhezj', '93766782', 'DIR', 'FIN', 'SG');
INSERT INTO salary (salary) VALUES (72000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('stlypzuprf', '90461303', 'DIR', 'FIN', 'HK');
INSERT INTO salary (salary) VALUES (43000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('xdholtvbnx', '98603622', 'DIR', 'FIN', 'EMEA');
INSERT INTO salary (salary) VALUES (86000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('mvwfqfbzxd', '95880227', 'DIR', 'FIN', 'LON');
INSERT INTO salary (salary) VALUES (47000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('egtiaytnib', '93895070', 'DIR', 'FIN', 'PAR');
INSERT INTO salary (salary) VALUES (55000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('ipqvsuzdqo', '98709989', 'DIR', 'FIN', 'AMER');
INSERT INTO salary (salary) VALUES (71000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('trkhjsviib', '91639267', 'DIR', 'FIN', 'NY');
INSERT INTO salary (salary) VALUES (65000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('dgaolfnbzb', '99406609', 'DIR', 'FIN', 'SF');
INSERT INTO salary (salary) VALUES (91000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('vbgfqhjpch', '91421579', 'MGR', 'FIN', 'GLOBAL');
INSERT INTO salary (salary) VALUES (61000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('iwtjkkikiq', '90709751', 'MGR', 'FIN', 'APAC');
INSERT INTO salary (salary) VALUES (91000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('zhtlcptzwm', '95035286', 'MGR', 'FIN', 'SG');
INSERT INTO salary (salary) VALUES (79000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('dmmffxktym', '93349060', 'MGR', 'FIN', 'HK');
INSERT INTO salary (salary) VALUES (76000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('uhpkvfzpnc', '93846980', 'MGR', 'FIN', 'EMEA');
INSERT INTO salary (salary) VALUES (85000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('djbdendhja', '96550202', 'MGR', 'FIN', 'LON');
INSERT INTO salary (salary) VALUES (100000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('sndgvdshuo', '97170369', 'MGR', 'FIN', 'PAR');
INSERT INTO salary (salary) VALUES (68000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('nnokgozjvk', '93044043', 'MGR', 'FIN', 'AMER');
INSERT INTO salary (salary) VALUES (59000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('yumdaztiqf', '97986742', 'MGR', 'FIN', 'NY');
INSERT INTO salary (salary) VALUES (69000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('wvlreuiuak', '91580029', 'MGR', 'FIN', 'SF');
INSERT INTO salary (salary) VALUES (78000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('nefosrqdfm', '96891309', 'EMP', 'FIN', 'GLOBAL');
INSERT INTO salary (salary) VALUES (55000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('zzqgagdyzv', '96257002', 'EMP', 'FIN', 'APAC');
INSERT INTO salary (salary) VALUES (44000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('ouczbbmwzw', '98316191', 'EMP', 'FIN', 'SG');
INSERT INTO salary (salary) VALUES (41000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('hcuidtnoxq', '95717546', 'EMP', 'FIN', 'HK');
INSERT INTO salary (salary) VALUES (42000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('awvgsicnli', '94763440', 'EMP', 'FIN', 'EMEA');
INSERT INTO salary (salary) VALUES (67000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('mqjvxnroau', '99653692', 'EMP', 'FIN', 'LON');
INSERT INTO salary (salary) VALUES (56000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('cfjbbxmiov', '91496990', 'EMP', 'FIN', 'PAR');
INSERT INTO salary (salary) VALUES (32000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('gcmnjclrtv', '98080564', 'EMP', 'FIN', 'AMER');
INSERT INTO salary (salary) VALUES (42000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('dvmobwuuxc', '94541885', 'EMP', 'FIN', 'NY');
INSERT INTO salary (salary) VALUES (100000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('otefiqhapk', '92965831', 'EMP', 'FIN', 'SF');
INSERT INTO salary (salary) VALUES (71000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('tqhvtjpxum', '94130992', 'DIR', 'ENG', 'GLOBAL');
INSERT INTO salary (salary) VALUES (44000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('vhcerdctcb', '99727601', 'DIR', 'ENG', 'APAC');
INSERT INTO salary (salary) VALUES (81000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('eorxecgjem', '92598507', 'DIR', 'ENG', 'SG');
INSERT INTO salary (salary) VALUES (66000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('rfddwpjbdj', '95609559', 'DIR', 'ENG', 'HK');
INSERT INTO salary (salary) VALUES (30000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('ygjqbtiuwu', '99580166', 'DIR', 'ENG', 'EMEA');
INSERT INTO salary (salary) VALUES (59000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('wgxoxmqldl', '94028992', 'DIR', 'ENG', 'LON');
INSERT INTO salary (salary) VALUES (50000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('nuehypfoys', '94678162', 'DIR', 'ENG', 'PAR');
INSERT INTO salary (salary) VALUES (94000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('sbjklmqniv', '98309425', 'DIR', 'ENG', 'AMER');
INSERT INTO salary (salary) VALUES (70000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('pgvqlbmigl', '96810839', 'DIR', 'ENG', 'NY');
INSERT INTO salary (salary) VALUES (70000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('dzjvvjqsnz', '96079319', 'DIR', 'ENG', 'SF');
INSERT INTO salary (salary) VALUES (82000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('dputrcqhth', '93439413', 'MGR', 'ENG', 'GLOBAL');
INSERT INTO salary (salary) VALUES (30000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('yffornsroq', '97938736', 'MGR', 'ENG', 'APAC');
INSERT INTO salary (salary) VALUES (72000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('jqqtpjvnub', '96559437', 'MGR', 'ENG', 'SG');
INSERT INTO salary (salary) VALUES (74000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('ssnnljgnjf', '97831936', 'MGR', 'ENG', 'HK');
INSERT INTO salary (salary) VALUES (90000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('opheaysldx', '98915845', 'MGR', 'ENG', 'EMEA');
INSERT INTO salary (salary) VALUES (50000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('mmdulvclnz', '98478464', 'MGR', 'ENG', 'LON');
INSERT INTO salary (salary) VALUES (50000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('glbkmpdfxi', '99652942', 'MGR', 'ENG', 'PAR');
INSERT INTO salary (salary) VALUES (96000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('wehjlllxkc', '95077915', 'MGR', 'ENG', 'AMER');
INSERT INTO salary (salary) VALUES (68000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('fvfexbrepa', '96429921', 'MGR', 'ENG', 'NY');
INSERT INTO salary (salary) VALUES (49000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('gabjmoqlko', '95759763', 'MGR', 'ENG', 'SF');
INSERT INTO salary (salary) VALUES (79000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('yiazydtxpi', '92982952', 'EMP', 'ENG', 'GLOBAL');
INSERT INTO salary (salary) VALUES (92000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('avsspwbkjc', '99586173', 'EMP', 'ENG', 'APAC');
INSERT INTO salary (salary) VALUES (50000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('odltietfnf', '98555167', 'EMP', 'ENG', 'SG');
INSERT INTO salary (salary) VALUES (40000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('zziolbcqdu', '94820035', 'EMP', 'ENG', 'HK');
INSERT INTO salary (salary) VALUES (50000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('rdjeugahnr', '98898694', 'EMP', 'ENG', 'EMEA');
INSERT INTO salary (salary) VALUES (34000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('dxigymerjs', '90996226', 'EMP', 'ENG', 'LON');
INSERT INTO salary (salary) VALUES (78000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('edcinhnaci', '91347530', 'EMP', 'ENG', 'PAR');
INSERT INTO salary (salary) VALUES (54000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('zvzsocjcjq', '95762184', 'EMP', 'ENG', 'AMER');
INSERT INTO salary (salary) VALUES (54000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('wypqmbvfnu', '90108729', 'EMP', 'ENG', 'NY');
INSERT INTO salary (salary) VALUES (53000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('zskacfpput', '93696546', 'EMP', 'ENG', 'SF');
INSERT INTO salary (salary) VALUES (85000);
