INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u1', '96487815', 'DIR', 'HR', 'GLOBAL');
INSERT INTO salary (emp_name, salary) VALUES ('u1', 52000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u2', '92068694', 'DIR', 'HR', 'APAC');
INSERT INTO salary (emp_name, salary) VALUES ('u2', 79000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u3', '92959277', 'DIR', 'HR', 'SG');
INSERT INTO salary (emp_name, salary) VALUES ('u3', 82000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u4', '99372960', 'DIR', 'HR', 'HK');
INSERT INTO salary (emp_name, salary) VALUES ('u4', 50000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u5', '93410576', 'DIR', 'HR', 'EMEA');
INSERT INTO salary (emp_name, salary) VALUES ('u5', 64000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u6', '92110261', 'DIR', 'HR', 'LON');
INSERT INTO salary (emp_name, salary) VALUES ('u6', 67000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u7', '95362235', 'DIR', 'HR', 'PAR');
INSERT INTO salary (emp_name, salary) VALUES ('u7', 65000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u8', '92035755', 'DIR', 'HR', 'AMER');
INSERT INTO salary (emp_name, salary) VALUES ('u8', 84000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u9', '98639368', 'DIR', 'HR', 'NY');
INSERT INTO salary (emp_name, salary) VALUES ('u9', 58000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u10', '91296788', 'DIR', 'HR', 'SF');
INSERT INTO salary (emp_name, salary) VALUES ('u10', 54000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u11', '92502199', 'MGR', 'HR', 'GLOBAL');
INSERT INTO salary (emp_name, salary) VALUES ('u11', 81000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u12', '94198095', 'MGR', 'HR', 'APAC');
INSERT INTO salary (emp_name, salary) VALUES ('u12', 42000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u13', '95243034', 'MGR', 'HR', 'SG');
INSERT INTO salary (emp_name, salary) VALUES ('u13', 45000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u14', '98681187', 'MGR', 'HR', 'HK');
INSERT INTO salary (emp_name, salary) VALUES ('u14', 36000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u15', '90211893', 'MGR', 'HR', 'EMEA');
INSERT INTO salary (emp_name, salary) VALUES ('u15', 84000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u16', '98212262', 'MGR', 'HR', 'LON');
INSERT INTO salary (emp_name, salary) VALUES ('u16', 55000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u17', '92318674', 'MGR', 'HR', 'PAR');
INSERT INTO salary (emp_name, salary) VALUES ('u17', 38000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u18', '99888323', 'MGR', 'HR', 'AMER');
INSERT INTO salary (emp_name, salary) VALUES ('u18', 74000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u19', '94910213', 'MGR', 'HR', 'NY');
INSERT INTO salary (emp_name, salary) VALUES ('u19', 64000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u20', '90541227', 'MGR', 'HR', 'SF');
INSERT INTO salary (emp_name, salary) VALUES ('u20', 50000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u21', '93484696', 'EMP', 'HR', 'GLOBAL');
INSERT INTO salary (emp_name, salary) VALUES ('u21', 73000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u22', '98270956', 'EMP', 'HR', 'APAC');
INSERT INTO salary (emp_name, salary) VALUES ('u22', 89000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u23', '99947900', 'EMP', 'HR', 'SG');
INSERT INTO salary (emp_name, salary) VALUES ('u23', 47000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u24', '97274104', 'EMP', 'HR', 'HK');
INSERT INTO salary (emp_name, salary) VALUES ('u24', 59000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u25', '97310642', 'EMP', 'HR', 'EMEA');
INSERT INTO salary (emp_name, salary) VALUES ('u25', 77000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u26', '94331973', 'EMP', 'HR', 'LON');
INSERT INTO salary (emp_name, salary) VALUES ('u26', 76000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u27', '95654908', 'EMP', 'HR', 'PAR');
INSERT INTO salary (emp_name, salary) VALUES ('u27', 46000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u28', '98200606', 'EMP', 'HR', 'AMER');
INSERT INTO salary (emp_name, salary) VALUES ('u28', 76000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u29', '91222640', 'EMP', 'HR', 'NY');
INSERT INTO salary (emp_name, salary) VALUES ('u29', 99000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u30', '90036883', 'EMP', 'HR', 'SF');
INSERT INTO salary (emp_name, salary) VALUES ('u30', 83000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u31', '90719141', 'DIR', 'FIN', 'GLOBAL');
INSERT INTO salary (emp_name, salary) VALUES ('u31', 83000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u32', '99112699', 'DIR', 'FIN', 'APAC');
INSERT INTO salary (emp_name, salary) VALUES ('u32', 32000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u33', '93120162', 'DIR', 'FIN', 'SG');
INSERT INTO salary (emp_name, salary) VALUES ('u33', 63000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u34', '99269109', 'DIR', 'FIN', 'HK');
INSERT INTO salary (emp_name, salary) VALUES ('u34', 58000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u35', '91279959', 'DIR', 'FIN', 'EMEA');
INSERT INTO salary (emp_name, salary) VALUES ('u35', 90000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u36', '98935147', 'DIR', 'FIN', 'LON');
INSERT INTO salary (emp_name, salary) VALUES ('u36', 83000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u37', '92213236', 'DIR', 'FIN', 'PAR');
INSERT INTO salary (emp_name, salary) VALUES ('u37', 100000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u38', '97260559', 'DIR', 'FIN', 'AMER');
INSERT INTO salary (emp_name, salary) VALUES ('u38', 31000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u39', '93183980', 'DIR', 'FIN', 'NY');
INSERT INTO salary (emp_name, salary) VALUES ('u39', 80000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u40', '90838934', 'DIR', 'FIN', 'SF');
INSERT INTO salary (emp_name, salary) VALUES ('u40', 87000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u41', '96894591', 'MGR', 'FIN', 'GLOBAL');
INSERT INTO salary (emp_name, salary) VALUES ('u41', 65000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u42', '90759383', 'MGR', 'FIN', 'APAC');
INSERT INTO salary (emp_name, salary) VALUES ('u42', 59000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u43', '94057349', 'MGR', 'FIN', 'SG');
INSERT INTO salary (emp_name, salary) VALUES ('u43', 52000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u44', '96305301', 'MGR', 'FIN', 'HK');
INSERT INTO salary (emp_name, salary) VALUES ('u44', 53000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u45', '98343913', 'MGR', 'FIN', 'EMEA');
INSERT INTO salary (emp_name, salary) VALUES ('u45', 72000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u46', '92550425', 'MGR', 'FIN', 'LON');
INSERT INTO salary (emp_name, salary) VALUES ('u46', 72000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u47', '94225604', 'MGR', 'FIN', 'PAR');
INSERT INTO salary (emp_name, salary) VALUES ('u47', 51000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u48', '92439777', 'MGR', 'FIN', 'AMER');
INSERT INTO salary (emp_name, salary) VALUES ('u48', 81000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u49', '93937229', 'MGR', 'FIN', 'NY');
INSERT INTO salary (emp_name, salary) VALUES ('u49', 34000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u50', '97553935', 'MGR', 'FIN', 'SF');
INSERT INTO salary (emp_name, salary) VALUES ('u50', 62000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u51', '97688029', 'EMP', 'FIN', 'GLOBAL');
INSERT INTO salary (emp_name, salary) VALUES ('u51', 32000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u52', '99360429', 'EMP', 'FIN', 'APAC');
INSERT INTO salary (emp_name, salary) VALUES ('u52', 62000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u53', '99979752', 'EMP', 'FIN', 'SG');
INSERT INTO salary (emp_name, salary) VALUES ('u53', 76000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u54', '98716525', 'EMP', 'FIN', 'HK');
INSERT INTO salary (emp_name, salary) VALUES ('u54', 51000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u55', '98993014', 'EMP', 'FIN', 'EMEA');
INSERT INTO salary (emp_name, salary) VALUES ('u55', 43000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u56', '92684081', 'EMP', 'FIN', 'LON');
INSERT INTO salary (emp_name, salary) VALUES ('u56', 63000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u57', '91084788', 'EMP', 'FIN', 'PAR');
INSERT INTO salary (emp_name, salary) VALUES ('u57', 92000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u58', '96373396', 'EMP', 'FIN', 'AMER');
INSERT INTO salary (emp_name, salary) VALUES ('u58', 53000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u59', '93371708', 'EMP', 'FIN', 'NY');
INSERT INTO salary (emp_name, salary) VALUES ('u59', 96000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u60', '95059316', 'EMP', 'FIN', 'SF');
INSERT INTO salary (emp_name, salary) VALUES ('u60', 48000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u61', '95335973', 'DIR', 'ENG', 'GLOBAL');
INSERT INTO salary (emp_name, salary) VALUES ('u61', 90000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u62', '90627945', 'DIR', 'ENG', 'APAC');
INSERT INTO salary (emp_name, salary) VALUES ('u62', 76000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u63', '91745525', 'DIR', 'ENG', 'SG');
INSERT INTO salary (emp_name, salary) VALUES ('u63', 54000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u64', '93201416', 'DIR', 'ENG', 'HK');
INSERT INTO salary (emp_name, salary) VALUES ('u64', 79000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u65', '90953414', 'DIR', 'ENG', 'EMEA');
INSERT INTO salary (emp_name, salary) VALUES ('u65', 55000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u66', '99651328', 'DIR', 'ENG', 'LON');
INSERT INTO salary (emp_name, salary) VALUES ('u66', 72000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u67', '92119676', 'DIR', 'ENG', 'PAR');
INSERT INTO salary (emp_name, salary) VALUES ('u67', 88000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u68', '96177123', 'DIR', 'ENG', 'AMER');
INSERT INTO salary (emp_name, salary) VALUES ('u68', 72000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u69', '93640308', 'DIR', 'ENG', 'NY');
INSERT INTO salary (emp_name, salary) VALUES ('u69', 49000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u70', '95317035', 'DIR', 'ENG', 'SF');
INSERT INTO salary (emp_name, salary) VALUES ('u70', 48000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u71', '95428270', 'MGR', 'ENG', 'GLOBAL');
INSERT INTO salary (emp_name, salary) VALUES ('u71', 32000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u72', '97596518', 'MGR', 'ENG', 'APAC');
INSERT INTO salary (emp_name, salary) VALUES ('u72', 86000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u73', '96662959', 'MGR', 'ENG', 'SG');
INSERT INTO salary (emp_name, salary) VALUES ('u73', 99000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u74', '95413867', 'MGR', 'ENG', 'HK');
INSERT INTO salary (emp_name, salary) VALUES ('u74', 69000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u75', '91819640', 'MGR', 'ENG', 'EMEA');
INSERT INTO salary (emp_name, salary) VALUES ('u75', 77000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u76', '94418236', 'MGR', 'ENG', 'LON');
INSERT INTO salary (emp_name, salary) VALUES ('u76', 32000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u77', '91934847', 'MGR', 'ENG', 'PAR');
INSERT INTO salary (emp_name, salary) VALUES ('u77', 80000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u78', '90489244', 'MGR', 'ENG', 'AMER');
INSERT INTO salary (emp_name, salary) VALUES ('u78', 58000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u79', '96858937', 'MGR', 'ENG', 'NY');
INSERT INTO salary (emp_name, salary) VALUES ('u79', 59000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u80', '98139295', 'MGR', 'ENG', 'SF');
INSERT INTO salary (emp_name, salary) VALUES ('u80', 83000);
COMMIT; 
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u81', '93096269', 'EMP', 'ENG', 'GLOBAL');
INSERT INTO salary (emp_name, salary) VALUES ('u81', 79000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u82', '95239424', 'EMP', 'ENG', 'APAC');
INSERT INTO salary (emp_name, salary) VALUES ('u82', 90000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u83', '91215337', 'EMP', 'ENG', 'SG');
INSERT INTO salary (emp_name, salary) VALUES ('u83', 52000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u84', '96372690', 'EMP', 'ENG', 'HK');
INSERT INTO salary (emp_name, salary) VALUES ('u84', 47000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u85', '90554337', 'EMP', 'ENG', 'EMEA');
INSERT INTO salary (emp_name, salary) VALUES ('u85', 93000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u86', '91553518', 'EMP', 'ENG', 'LON');
INSERT INTO salary (emp_name, salary) VALUES ('u86', 86000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u87', '98603420', 'EMP', 'ENG', 'PAR');
INSERT INTO salary (emp_name, salary) VALUES ('u87', 64000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u88', '94569601', 'EMP', 'ENG', 'AMER');
INSERT INTO salary (emp_name, salary) VALUES ('u88', 77000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u89', '90096296', 'EMP', 'ENG', 'NY');
INSERT INTO salary (emp_name, salary) VALUES ('u89', 69000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u90', '95098522', 'EMP', 'ENG', 'SF');
INSERT INTO salary (emp_name, salary) VALUES ('u90', 45000);
UPDATE salary SET sal_label = gen_sal_label(emp_name); 
COMMIT; 
