INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p1', 'desc1', 'U', 'FE', 'GLOBAL');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p1', 84000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p2', 'desc2', 'U', 'FE', 'APAC');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p2', 52000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p3', 'desc3', 'U', 'FE', 'SG');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p3', 74000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p4', 'desc4', 'U', 'FE', 'HK');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p4', 100000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p5', 'desc5', 'U', 'FE', 'EMEA');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p5', 98000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p6', 'desc6', 'U', 'FE', 'LON');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p6', 76000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p7', 'desc7', 'U', 'FE', 'PAR');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p7', 34000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p8', 'desc8', 'U', 'FE', 'AMER');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p8', 92000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p9', 'desc9', 'U', 'FE', 'NY');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p9', 84000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p10', 'desc10', 'U', 'FE', 'SF');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p10', 97000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p11', 'desc11', 'U', 'BE', 'GLOBAL');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p11', 45000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p12', 'desc12', 'U', 'BE', 'APAC');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p12', 98000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p13', 'desc13', 'U', 'BE', 'SG');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p13', 68000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p14', 'desc14', 'U', 'BE', 'HK');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p14', 40000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p15', 'desc15', 'U', 'BE', 'EMEA');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p15', 61000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p16', 'desc16', 'U', 'BE', 'LON');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p16', 37000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p17', 'desc17', 'U', 'BE', 'PAR');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p17', 63000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p18', 'desc18', 'U', 'BE', 'AMER');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p18', 36000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p19', 'desc19', 'U', 'BE', 'NY');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p19', 73000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p20', 'desc20', 'U', 'BE', 'SF');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p20', 63000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p21', 'desc21', 'U', 'SEC', 'GLOBAL');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p21', 64000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p22', 'desc22', 'U', 'SEC', 'APAC');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p22', 76000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p23', 'desc23', 'U', 'SEC', 'SG');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p23', 76000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p24', 'desc24', 'U', 'SEC', 'HK');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p24', 71000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p25', 'desc25', 'U', 'SEC', 'EMEA');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p25', 57000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p26', 'desc26', 'U', 'SEC', 'LON');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p26', 52000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p27', 'desc27', 'U', 'SEC', 'PAR');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p27', 79000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p28', 'desc28', 'U', 'SEC', 'AMER');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p28', 32000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p29', 'desc29', 'U', 'SEC', 'NY');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p29', 95000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p30', 'desc30', 'U', 'SEC', 'SF');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p30', 42000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p31', 'desc31', 'U', 'DEV', 'GLOBAL');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p31', 62000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p32', 'desc32', 'U', 'DEV', 'APAC');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p32', 49000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p33', 'desc33', 'U', 'DEV', 'SG');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p33', 83000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p34', 'desc34', 'U', 'DEV', 'HK');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p34', 39000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p35', 'desc35', 'U', 'DEV', 'EMEA');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p35', 50000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p36', 'desc36', 'U', 'DEV', 'LON');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p36', 33000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p37', 'desc37', 'U', 'DEV', 'PAR');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p37', 91000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p38', 'desc38', 'U', 'DEV', 'AMER');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p38', 95000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p39', 'desc39', 'U', 'DEV', 'NY');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p39', 96000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p40', 'desc40', 'U', 'DEV', 'SF');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p40', 77000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p41', 'desc41', 'C', 'FE', 'GLOBAL');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p41', 54000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p42', 'desc42', 'C', 'FE', 'APAC');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p42', 44000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p43', 'desc43', 'C', 'FE', 'SG');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p43', 69000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p44', 'desc44', 'C', 'FE', 'HK');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p44', 89000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p45', 'desc45', 'C', 'FE', 'EMEA');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p45', 37000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p46', 'desc46', 'C', 'FE', 'LON');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p46', 97000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p47', 'desc47', 'C', 'FE', 'PAR');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p47', 67000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p48', 'desc48', 'C', 'FE', 'AMER');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p48', 70000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p49', 'desc49', 'C', 'FE', 'NY');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p49', 74000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p50', 'desc50', 'C', 'FE', 'SF');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p50', 64000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p51', 'desc51', 'C', 'BE', 'GLOBAL');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p51', 90000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p52', 'desc52', 'C', 'BE', 'APAC');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p52', 64000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p53', 'desc53', 'C', 'BE', 'SG');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p53', 54000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p54', 'desc54', 'C', 'BE', 'HK');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p54', 76000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p55', 'desc55', 'C', 'BE', 'EMEA');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p55', 45000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p56', 'desc56', 'C', 'BE', 'LON');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p56', 34000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p57', 'desc57', 'C', 'BE', 'PAR');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p57', 48000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p58', 'desc58', 'C', 'BE', 'AMER');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p58', 46000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p59', 'desc59', 'C', 'BE', 'NY');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p59', 97000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p60', 'desc60', 'C', 'BE', 'SF');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p60', 75000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p61', 'desc61', 'C', 'SEC', 'GLOBAL');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p61', 58000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p62', 'desc62', 'C', 'SEC', 'APAC');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p62', 41000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p63', 'desc63', 'C', 'SEC', 'SG');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p63', 49000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p64', 'desc64', 'C', 'SEC', 'HK');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p64', 91000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p65', 'desc65', 'C', 'SEC', 'EMEA');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p65', 93000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p66', 'desc66', 'C', 'SEC', 'LON');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p66', 44000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p67', 'desc67', 'C', 'SEC', 'PAR');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p67', 63000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p68', 'desc68', 'C', 'SEC', 'AMER');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p68', 84000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p69', 'desc69', 'C', 'SEC', 'NY');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p69', 31000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p70', 'desc70', 'C', 'SEC', 'SF');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p70', 83000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p71', 'desc71', 'C', 'DEV', 'GLOBAL');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p71', 78000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p72', 'desc72', 'C', 'DEV', 'APAC');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p72', 55000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p73', 'desc73', 'C', 'DEV', 'SG');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p73', 63000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p74', 'desc74', 'C', 'DEV', 'HK');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p74', 66000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p75', 'desc75', 'C', 'DEV', 'EMEA');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p75', 100000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p76', 'desc76', 'C', 'DEV', 'LON');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p76', 65000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p77', 'desc77', 'C', 'DEV', 'PAR');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p77', 84000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p78', 'desc78', 'C', 'DEV', 'AMER');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p78', 59000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p79', 'desc79', 'C', 'DEV', 'NY');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p79', 77000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p80', 'desc80', 'C', 'DEV', 'SF');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p80', 43000);
COMMIT; 
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p81', 'desc81', 'S', 'FE', 'GLOBAL');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p81', 55000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p82', 'desc82', 'S', 'FE', 'APAC');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p82', 97000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p83', 'desc83', 'S', 'FE', 'SG');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p83', 45000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p84', 'desc84', 'S', 'FE', 'HK');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p84', 57000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p85', 'desc85', 'S', 'FE', 'EMEA');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p85', 87000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p86', 'desc86', 'S', 'FE', 'LON');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p86', 90000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p87', 'desc87', 'S', 'FE', 'PAR');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p87', 61000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p88', 'desc88', 'S', 'FE', 'AMER');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p88', 50000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p89', 'desc89', 'S', 'FE', 'NY');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p89', 56000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p90', 'desc90', 'S', 'FE', 'SF');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p90', 38000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p91', 'desc91', 'S', 'BE', 'GLOBAL');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p91', 67000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p92', 'desc92', 'S', 'BE', 'APAC');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p92', 61000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p93', 'desc93', 'S', 'BE', 'SG');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p93', 88000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p94', 'desc94', 'S', 'BE', 'HK');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p94', 94000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p95', 'desc95', 'S', 'BE', 'EMEA');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p95', 34000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p96', 'desc96', 'S', 'BE', 'LON');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p96', 73000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p97', 'desc97', 'S', 'BE', 'PAR');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p97', 31000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p98', 'desc98', 'S', 'BE', 'AMER');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p98', 93000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p99', 'desc99', 'S', 'BE', 'NY');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p99', 64000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p100', 'desc100', 'S', 'BE', 'SF');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p100', 54000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p101', 'desc101', 'S', 'SEC', 'GLOBAL');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p101', 46000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p102', 'desc102', 'S', 'SEC', 'APAC');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p102', 78000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p103', 'desc103', 'S', 'SEC', 'SG');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p103', 34000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p104', 'desc104', 'S', 'SEC', 'HK');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p104', 99000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p105', 'desc105', 'S', 'SEC', 'EMEA');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p105', 53000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p106', 'desc106', 'S', 'SEC', 'LON');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p106', 63000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p107', 'desc107', 'S', 'SEC', 'PAR');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p107', 93000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p108', 'desc108', 'S', 'SEC', 'AMER');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p108', 78000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p109', 'desc109', 'S', 'SEC', 'NY');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p109', 91000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p110', 'desc110', 'S', 'SEC', 'SF');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p110', 83000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p111', 'desc111', 'S', 'DEV', 'GLOBAL');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p111', 71000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p112', 'desc112', 'S', 'DEV', 'APAC');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p112', 52000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p113', 'desc113', 'S', 'DEV', 'SG');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p113', 64000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p114', 'desc114', 'S', 'DEV', 'HK');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p114', 91000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p115', 'desc115', 'S', 'DEV', 'EMEA');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p115', 87000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p116', 'desc116', 'S', 'DEV', 'LON');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p116', 58000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p117', 'desc117', 'S', 'DEV', 'PAR');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p117', 77000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p118', 'desc118', 'S', 'DEV', 'AMER');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p118', 54000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p119', 'desc119', 'S', 'DEV', 'NY');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p119', 50000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('p120', 'desc120', 'S', 'DEV', 'SF');
INSERT INTO project_budgets (proj_name, budget) VALUES ('p120', 56000);
UPDATE project_budgets SET budget_label = gen_budget_label(proj_name); 
COMMIT; 
