INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u1', '97685230', 'DIR', 'HR', 'GLOBAL');
INSERT INTO salary (emp_name, salary) VALUES ('u1', 41000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u2', '93338096', 'DIR', 'HR', 'APAC');
INSERT INTO salary (emp_name, salary) VALUES ('u2', 69000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u3', '97711807', 'DIR', 'HR', 'SG');
INSERT INTO salary (emp_name, salary) VALUES ('u3', 36000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u4', '91817292', 'DIR', 'HR', 'HK');
INSERT INTO salary (emp_name, salary) VALUES ('u4', 82000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u5', '94923309', 'DIR', 'HR', 'EMEA');
INSERT INTO salary (emp_name, salary) VALUES ('u5', 54000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u6', '95947577', 'DIR', 'HR', 'LON');
INSERT INTO salary (emp_name, salary) VALUES ('u6', 71000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u7', '99578217', 'DIR', 'HR', 'PAR');
INSERT INTO salary (emp_name, salary) VALUES ('u7', 62000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u8', '91036621', 'DIR', 'HR', 'AMER');
INSERT INTO salary (emp_name, salary) VALUES ('u8', 63000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u9', '99135804', 'DIR', 'HR', 'NY');
INSERT INTO salary (emp_name, salary) VALUES ('u9', 80000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u10', '98290829', 'DIR', 'HR', 'SF');
INSERT INTO salary (emp_name, salary) VALUES ('u10', 44000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u11', '98164923', 'MGR', 'HR', 'GLOBAL');
INSERT INTO salary (emp_name, salary) VALUES ('u11', 81000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u12', '97453621', 'MGR', 'HR', 'APAC');
INSERT INTO salary (emp_name, salary) VALUES ('u12', 96000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u13', '95938921', 'MGR', 'HR', 'SG');
INSERT INTO salary (emp_name, salary) VALUES ('u13', 95000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u14', '93856025', 'MGR', 'HR', 'HK');
INSERT INTO salary (emp_name, salary) VALUES ('u14', 45000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u15', '97311618', 'MGR', 'HR', 'EMEA');
INSERT INTO salary (emp_name, salary) VALUES ('u15', 80000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u16', '93937500', 'MGR', 'HR', 'LON');
INSERT INTO salary (emp_name, salary) VALUES ('u16', 44000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u17', '94502435', 'MGR', 'HR', 'PAR');
INSERT INTO salary (emp_name, salary) VALUES ('u17', 42000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u18', '92444269', 'MGR', 'HR', 'AMER');
INSERT INTO salary (emp_name, salary) VALUES ('u18', 35000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u19', '96479242', 'MGR', 'HR', 'NY');
INSERT INTO salary (emp_name, salary) VALUES ('u19', 82000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u20', '96353794', 'MGR', 'HR', 'SF');
INSERT INTO salary (emp_name, salary) VALUES ('u20', 95000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u21', '99689040', 'EMP', 'HR', 'GLOBAL');
INSERT INTO salary (emp_name, salary) VALUES ('u21', 44000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u22', '99639716', 'EMP', 'HR', 'APAC');
INSERT INTO salary (emp_name, salary) VALUES ('u22', 61000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u23', '93505105', 'EMP', 'HR', 'SG');
INSERT INTO salary (emp_name, salary) VALUES ('u23', 56000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u24', '99102186', 'EMP', 'HR', 'HK');
INSERT INTO salary (emp_name, salary) VALUES ('u24', 84000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u25', '95583177', 'EMP', 'HR', 'EMEA');
INSERT INTO salary (emp_name, salary) VALUES ('u25', 99000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u26', '98087699', 'EMP', 'HR', 'LON');
INSERT INTO salary (emp_name, salary) VALUES ('u26', 98000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u27', '96749671', 'EMP', 'HR', 'PAR');
INSERT INTO salary (emp_name, salary) VALUES ('u27', 31000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u28', '90382416', 'EMP', 'HR', 'AMER');
INSERT INTO salary (emp_name, salary) VALUES ('u28', 43000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u29', '98154787', 'EMP', 'HR', 'NY');
INSERT INTO salary (emp_name, salary) VALUES ('u29', 56000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u30', '96819955', 'EMP', 'HR', 'SF');
INSERT INTO salary (emp_name, salary) VALUES ('u30', 41000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u31', '97226484', 'DIR', 'FIN', 'GLOBAL');
INSERT INTO salary (emp_name, salary) VALUES ('u31', 31000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u32', '95831902', 'DIR', 'FIN', 'APAC');
INSERT INTO salary (emp_name, salary) VALUES ('u32', 82000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u33', '97841448', 'DIR', 'FIN', 'SG');
INSERT INTO salary (emp_name, salary) VALUES ('u33', 47000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u34', '93652593', 'DIR', 'FIN', 'HK');
INSERT INTO salary (emp_name, salary) VALUES ('u34', 92000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u35', '91177403', 'DIR', 'FIN', 'EMEA');
INSERT INTO salary (emp_name, salary) VALUES ('u35', 93000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u36', '99266440', 'DIR', 'FIN', 'LON');
INSERT INTO salary (emp_name, salary) VALUES ('u36', 49000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u37', '93366169', 'DIR', 'FIN', 'PAR');
INSERT INTO salary (emp_name, salary) VALUES ('u37', 67000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u38', '91385394', 'DIR', 'FIN', 'AMER');
INSERT INTO salary (emp_name, salary) VALUES ('u38', 33000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u39', '94504404', 'DIR', 'FIN', 'NY');
INSERT INTO salary (emp_name, salary) VALUES ('u39', 77000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u40', '96876522', 'DIR', 'FIN', 'SF');
INSERT INTO salary (emp_name, salary) VALUES ('u40', 72000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u41', '95069965', 'MGR', 'FIN', 'GLOBAL');
INSERT INTO salary (emp_name, salary) VALUES ('u41', 58000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u42', '91303071', 'MGR', 'FIN', 'APAC');
INSERT INTO salary (emp_name, salary) VALUES ('u42', 89000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u43', '96597452', 'MGR', 'FIN', 'SG');
INSERT INTO salary (emp_name, salary) VALUES ('u43', 51000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u44', '90122767', 'MGR', 'FIN', 'HK');
INSERT INTO salary (emp_name, salary) VALUES ('u44', 73000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u45', '95073490', 'MGR', 'FIN', 'EMEA');
INSERT INTO salary (emp_name, salary) VALUES ('u45', 35000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u46', '98165020', 'MGR', 'FIN', 'LON');
INSERT INTO salary (emp_name, salary) VALUES ('u46', 50000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u47', '93377197', 'MGR', 'FIN', 'PAR');
INSERT INTO salary (emp_name, salary) VALUES ('u47', 73000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u48', '94032165', 'MGR', 'FIN', 'AMER');
INSERT INTO salary (emp_name, salary) VALUES ('u48', 77000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u49', '90048312', 'MGR', 'FIN', 'NY');
INSERT INTO salary (emp_name, salary) VALUES ('u49', 73000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u50', '95296397', 'MGR', 'FIN', 'SF');
INSERT INTO salary (emp_name, salary) VALUES ('u50', 78000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u51', '90682388', 'EMP', 'FIN', 'GLOBAL');
INSERT INTO salary (emp_name, salary) VALUES ('u51', 95000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u52', '99411894', 'EMP', 'FIN', 'APAC');
INSERT INTO salary (emp_name, salary) VALUES ('u52', 56000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u53', '96986564', 'EMP', 'FIN', 'SG');
INSERT INTO salary (emp_name, salary) VALUES ('u53', 68000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u54', '99947845', 'EMP', 'FIN', 'HK');
INSERT INTO salary (emp_name, salary) VALUES ('u54', 65000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u55', '90791429', 'EMP', 'FIN', 'EMEA');
INSERT INTO salary (emp_name, salary) VALUES ('u55', 38000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u56', '99433741', 'EMP', 'FIN', 'LON');
INSERT INTO salary (emp_name, salary) VALUES ('u56', 66000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u57', '99012997', 'EMP', 'FIN', 'PAR');
INSERT INTO salary (emp_name, salary) VALUES ('u57', 46000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u58', '99360541', 'EMP', 'FIN', 'AMER');
INSERT INTO salary (emp_name, salary) VALUES ('u58', 44000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u59', '97576998', 'EMP', 'FIN', 'NY');
INSERT INTO salary (emp_name, salary) VALUES ('u59', 74000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u60', '95099147', 'EMP', 'FIN', 'SF');
INSERT INTO salary (emp_name, salary) VALUES ('u60', 85000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u61', '90487191', 'DIR', 'ENG', 'GLOBAL');
INSERT INTO salary (emp_name, salary) VALUES ('u61', 99000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u62', '94264748', 'DIR', 'ENG', 'APAC');
INSERT INTO salary (emp_name, salary) VALUES ('u62', 68000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u63', '91086307', 'DIR', 'ENG', 'SG');
INSERT INTO salary (emp_name, salary) VALUES ('u63', 76000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u64', '97754442', 'DIR', 'ENG', 'HK');
INSERT INTO salary (emp_name, salary) VALUES ('u64', 46000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u65', '91789209', 'DIR', 'ENG', 'EMEA');
INSERT INTO salary (emp_name, salary) VALUES ('u65', 97000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u66', '94515978', 'DIR', 'ENG', 'LON');
INSERT INTO salary (emp_name, salary) VALUES ('u66', 69000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u67', '91944858', 'DIR', 'ENG', 'PAR');
INSERT INTO salary (emp_name, salary) VALUES ('u67', 69000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u68', '96568939', 'DIR', 'ENG', 'AMER');
INSERT INTO salary (emp_name, salary) VALUES ('u68', 56000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u69', '91070298', 'DIR', 'ENG', 'NY');
INSERT INTO salary (emp_name, salary) VALUES ('u69', 91000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u70', '96469558', 'DIR', 'ENG', 'SF');
INSERT INTO salary (emp_name, salary) VALUES ('u70', 70000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u71', '96520960', 'MGR', 'ENG', 'GLOBAL');
INSERT INTO salary (emp_name, salary) VALUES ('u71', 34000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u72', '97380949', 'MGR', 'ENG', 'APAC');
INSERT INTO salary (emp_name, salary) VALUES ('u72', 35000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u73', '96389737', 'MGR', 'ENG', 'SG');
INSERT INTO salary (emp_name, salary) VALUES ('u73', 49000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u74', '97341925', 'MGR', 'ENG', 'HK');
INSERT INTO salary (emp_name, salary) VALUES ('u74', 74000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u75', '98146160', 'MGR', 'ENG', 'EMEA');
INSERT INTO salary (emp_name, salary) VALUES ('u75', 64000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u76', '92829379', 'MGR', 'ENG', 'LON');
INSERT INTO salary (emp_name, salary) VALUES ('u76', 44000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u77', '91830688', 'MGR', 'ENG', 'PAR');
INSERT INTO salary (emp_name, salary) VALUES ('u77', 40000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u78', '96078489', 'MGR', 'ENG', 'AMER');
INSERT INTO salary (emp_name, salary) VALUES ('u78', 97000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u79', '91288826', 'MGR', 'ENG', 'NY');
INSERT INTO salary (emp_name, salary) VALUES ('u79', 60000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u80', '98906166', 'MGR', 'ENG', 'SF');
INSERT INTO salary (emp_name, salary) VALUES ('u80', 75000);
COMMIT; 
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u81', '94555880', 'EMP', 'ENG', 'GLOBAL');
INSERT INTO salary (emp_name, salary) VALUES ('u81', 74000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u82', '95577108', 'EMP', 'ENG', 'APAC');
INSERT INTO salary (emp_name, salary) VALUES ('u82', 51000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u83', '92736112', 'EMP', 'ENG', 'SG');
INSERT INTO salary (emp_name, salary) VALUES ('u83', 53000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u84', '91653423', 'EMP', 'ENG', 'HK');
INSERT INTO salary (emp_name, salary) VALUES ('u84', 73000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u85', '95219109', 'EMP', 'ENG', 'EMEA');
INSERT INTO salary (emp_name, salary) VALUES ('u85', 56000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u86', '99966090', 'EMP', 'ENG', 'LON');
INSERT INTO salary (emp_name, salary) VALUES ('u86', 65000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u87', '92550885', 'EMP', 'ENG', 'PAR');
INSERT INTO salary (emp_name, salary) VALUES ('u87', 32000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u88', '95671704', 'EMP', 'ENG', 'AMER');
INSERT INTO salary (emp_name, salary) VALUES ('u88', 74000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u89', '95073487', 'EMP', 'ENG', 'NY');
INSERT INTO salary (emp_name, salary) VALUES ('u89', 58000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u90', '96706744', 'EMP', 'ENG', 'SF');
INSERT INTO salary (emp_name, salary) VALUES ('u90', 76000);
COMMIT; 
