INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u1', '94539573', 'DIR', 'HR', 'GLOBAL');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u1', 72000, gen_sal_label('u1'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u2', '91151963', 'DIR', 'HR', 'APAC');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u2', 70000, gen_sal_label('u2'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u3', '96412067', 'DIR', 'HR', 'SG');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u3', 62000, gen_sal_label('u3'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u4', '92933750', 'DIR', 'HR', 'HK');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u4', 53000, gen_sal_label('u4'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u5', '92834007', 'DIR', 'HR', 'EMEA');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u5', 76000, gen_sal_label('u5'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u6', '93372387', 'DIR', 'HR', 'LON');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u6', 66000, gen_sal_label('u6'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u7', '91709314', 'DIR', 'HR', 'PAR');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u7', 84000, gen_sal_label('u7'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u8', '91331768', 'DIR', 'HR', 'AMER');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u8', 40000, gen_sal_label('u8'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u9', '96904631', 'DIR', 'HR', 'NY');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u9', 74000, gen_sal_label('u9'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u10', '90676314', 'DIR', 'HR', 'SF');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u10', 41000, gen_sal_label('u10'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u11', '94604965', 'MGR', 'HR', 'GLOBAL');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u11', 90000, gen_sal_label('u11'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u12', '96145643', 'MGR', 'HR', 'APAC');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u12', 83000, gen_sal_label('u12'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u13', '90599115', 'MGR', 'HR', 'SG');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u13', 84000, gen_sal_label('u13'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u14', '91147533', 'MGR', 'HR', 'HK');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u14', 32000, gen_sal_label('u14'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u15', '92979718', 'MGR', 'HR', 'EMEA');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u15', 63000, gen_sal_label('u15'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u16', '90814250', 'MGR', 'HR', 'LON');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u16', 36000, gen_sal_label('u16'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u17', '90596850', 'MGR', 'HR', 'PAR');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u17', 57000, gen_sal_label('u17'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u18', '98538569', 'MGR', 'HR', 'AMER');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u18', 34000, gen_sal_label('u18'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u19', '99178583', 'MGR', 'HR', 'NY');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u19', 66000, gen_sal_label('u19'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u20', '97787284', 'MGR', 'HR', 'SF');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u20', 87000, gen_sal_label('u20'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u21', '98038840', 'EMP', 'HR', 'GLOBAL');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u21', 96000, gen_sal_label('u21'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u22', '90062634', 'EMP', 'HR', 'APAC');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u22', 55000, gen_sal_label('u22'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u23', '97478073', 'EMP', 'HR', 'SG');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u23', 59000, gen_sal_label('u23'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u24', '93717017', 'EMP', 'HR', 'HK');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u24', 65000, gen_sal_label('u24'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u25', '96036768', 'EMP', 'HR', 'EMEA');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u25', 54000, gen_sal_label('u25'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u26', '95449814', 'EMP', 'HR', 'LON');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u26', 48000, gen_sal_label('u26'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u27', '98706487', 'EMP', 'HR', 'PAR');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u27', 96000, gen_sal_label('u27'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u28', '98405314', 'EMP', 'HR', 'AMER');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u28', 79000, gen_sal_label('u28'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u29', '98858961', 'EMP', 'HR', 'NY');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u29', 30000, gen_sal_label('u29'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u30', '94658691', 'EMP', 'HR', 'SF');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u30', 93000, gen_sal_label('u30'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u31', '97998667', 'DIR', 'FIN', 'GLOBAL');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u31', 79000, gen_sal_label('u31'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u32', '94276641', 'DIR', 'FIN', 'APAC');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u32', 87000, gen_sal_label('u32'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u33', '90672220', 'DIR', 'FIN', 'SG');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u33', 99000, gen_sal_label('u33'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u34', '92244190', 'DIR', 'FIN', 'HK');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u34', 66000, gen_sal_label('u34'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u35', '95013316', 'DIR', 'FIN', 'EMEA');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u35', 77000, gen_sal_label('u35'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u36', '96754955', 'DIR', 'FIN', 'LON');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u36', 85000, gen_sal_label('u36'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u37', '99939913', 'DIR', 'FIN', 'PAR');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u37', 72000, gen_sal_label('u37'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u38', '99165596', 'DIR', 'FIN', 'AMER');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u38', 74000, gen_sal_label('u38'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u39', '93548647', 'DIR', 'FIN', 'NY');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u39', 68000, gen_sal_label('u39'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u40', '91810982', 'DIR', 'FIN', 'SF');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u40', 62000, gen_sal_label('u40'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u41', '94730215', 'MGR', 'FIN', 'GLOBAL');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u41', 59000, gen_sal_label('u41'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u42', '92477111', 'MGR', 'FIN', 'APAC');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u42', 87000, gen_sal_label('u42'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u43', '97978818', 'MGR', 'FIN', 'SG');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u43', 93000, gen_sal_label('u43'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u44', '92884534', 'MGR', 'FIN', 'HK');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u44', 54000, gen_sal_label('u44'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u45', '97291401', 'MGR', 'FIN', 'EMEA');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u45', 77000, gen_sal_label('u45'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u46', '91776640', 'MGR', 'FIN', 'LON');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u46', 45000, gen_sal_label('u46'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u47', '90953965', 'MGR', 'FIN', 'PAR');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u47', 43000, gen_sal_label('u47'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u48', '91813420', 'MGR', 'FIN', 'AMER');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u48', 48000, gen_sal_label('u48'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u49', '91031279', 'MGR', 'FIN', 'NY');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u49', 83000, gen_sal_label('u49'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u50', '93388742', 'MGR', 'FIN', 'SF');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u50', 83000, gen_sal_label('u50'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u51', '96848210', 'EMP', 'FIN', 'GLOBAL');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u51', 67000, gen_sal_label('u51'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u52', '97824982', 'EMP', 'FIN', 'APAC');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u52', 33000, gen_sal_label('u52'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u53', '94352148', 'EMP', 'FIN', 'SG');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u53', 65000, gen_sal_label('u53'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u54', '93773012', 'EMP', 'FIN', 'HK');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u54', 86000, gen_sal_label('u54'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u55', '99665804', 'EMP', 'FIN', 'EMEA');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u55', 60000, gen_sal_label('u55'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u56', '98961743', 'EMP', 'FIN', 'LON');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u56', 66000, gen_sal_label('u56'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u57', '99150632', 'EMP', 'FIN', 'PAR');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u57', 87000, gen_sal_label('u57'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u58', '94803631', 'EMP', 'FIN', 'AMER');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u58', 82000, gen_sal_label('u58'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u59', '94993669', 'EMP', 'FIN', 'NY');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u59', 72000, gen_sal_label('u59'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u60', '99647714', 'EMP', 'FIN', 'SF');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u60', 48000, gen_sal_label('u60'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u61', '94765843', 'DIR', 'ENG', 'GLOBAL');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u61', 36000, gen_sal_label('u61'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u62', '92763567', 'DIR', 'ENG', 'APAC');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u62', 78000, gen_sal_label('u62'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u63', '93962563', 'DIR', 'ENG', 'SG');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u63', 100000, gen_sal_label('u63'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u64', '96607228', 'DIR', 'ENG', 'HK');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u64', 93000, gen_sal_label('u64'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u65', '96045806', 'DIR', 'ENG', 'EMEA');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u65', 94000, gen_sal_label('u65'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u66', '97569991', 'DIR', 'ENG', 'LON');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u66', 72000, gen_sal_label('u66'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u67', '92244041', 'DIR', 'ENG', 'PAR');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u67', 56000, gen_sal_label('u67'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u68', '99189496', 'DIR', 'ENG', 'AMER');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u68', 65000, gen_sal_label('u68'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u69', '92186040', 'DIR', 'ENG', 'NY');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u69', 54000, gen_sal_label('u69'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u70', '90213637', 'DIR', 'ENG', 'SF');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u70', 74000, gen_sal_label('u70'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u71', '92456105', 'MGR', 'ENG', 'GLOBAL');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u71', 96000, gen_sal_label('u71'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u72', '92329611', 'MGR', 'ENG', 'APAC');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u72', 61000, gen_sal_label('u72'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u73', '96311087', 'MGR', 'ENG', 'SG');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u73', 71000, gen_sal_label('u73'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u74', '96071866', 'MGR', 'ENG', 'HK');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u74', 83000, gen_sal_label('u74'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u75', '91791112', 'MGR', 'ENG', 'EMEA');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u75', 67000, gen_sal_label('u75'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u76', '94936138', 'MGR', 'ENG', 'LON');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u76', 86000, gen_sal_label('u76'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u77', '97932734', 'MGR', 'ENG', 'PAR');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u77', 73000, gen_sal_label('u77'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u78', '96656821', 'MGR', 'ENG', 'AMER');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u78', 48000, gen_sal_label('u78'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u79', '93904754', 'MGR', 'ENG', 'NY');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u79', 82000, gen_sal_label('u79'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u80', '99743787', 'MGR', 'ENG', 'SF');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u80', 96000, gen_sal_label('u80'));
COMMIT; 
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u81', '98130917', 'EMP', 'ENG', 'GLOBAL');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u81', 33000, gen_sal_label('u81'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u82', '92804501', 'EMP', 'ENG', 'APAC');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u82', 72000, gen_sal_label('u82'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u83', '96559965', 'EMP', 'ENG', 'SG');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u83', 77000, gen_sal_label('u83'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u84', '96907047', 'EMP', 'ENG', 'HK');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u84', 33000, gen_sal_label('u84'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u85', '97978110', 'EMP', 'ENG', 'EMEA');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u85', 51000, gen_sal_label('u85'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u86', '96824421', 'EMP', 'ENG', 'LON');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u86', 39000, gen_sal_label('u86'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u87', '93204493', 'EMP', 'ENG', 'PAR');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u87', 81000, gen_sal_label('u87'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u88', '99628726', 'EMP', 'ENG', 'AMER');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u88', 41000, gen_sal_label('u88'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u89', '90531494', 'EMP', 'ENG', 'NY');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u89', 42000, gen_sal_label('u89'));
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('u90', '96875993', 'EMP', 'ENG', 'SF');
INSERT INTO salary (emp_name, salary, sal_label) VALUES ('u90', 96000, gen_sal_label('u90'));
COMMIT; 
