INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('xzkprjdnqi', '96384224', 'DIR', 'HR', 'GLOBAL');
INSERT INTO salary (emp_name, salary) VALUES ('xzkprjdnqi', 64000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('cuteibwici', '92360289', 'DIR', 'HR', 'APAC');
INSERT INTO salary (emp_name, salary) VALUES ('cuteibwici', 79000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('wkpmskvfji', '90861190', 'DIR', 'HR', 'SG');
INSERT INTO salary (emp_name, salary) VALUES ('wkpmskvfji', 72000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('umowbrymsy', '94053543', 'DIR', 'HR', 'HK');
INSERT INTO salary (emp_name, salary) VALUES ('umowbrymsy', 42000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('opefohpxdo', '92644387', 'DIR', 'HR', 'EMEA');
INSERT INTO salary (emp_name, salary) VALUES ('opefohpxdo', 96000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('lcagiiqsrh', '91585436', 'DIR', 'HR', 'LON');
INSERT INTO salary (emp_name, salary) VALUES ('lcagiiqsrh', 45000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('behxkpnfja', '92812311', 'DIR', 'HR', 'PAR');
INSERT INTO salary (emp_name, salary) VALUES ('behxkpnfja', 47000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('yffqalmpfc', '99152554', 'DIR', 'HR', 'AMER');
INSERT INTO salary (emp_name, salary) VALUES ('yffqalmpfc', 43000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('gbwrsqqmoh', '90910990', 'DIR', 'HR', 'NY');
INSERT INTO salary (emp_name, salary) VALUES ('gbwrsqqmoh', 57000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('zcpkhswopj', '92527450', 'DIR', 'HR', 'SF');
INSERT INTO salary (emp_name, salary) VALUES ('zcpkhswopj', 57000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('qnteeaussy', '95906109', 'MGR', 'HR', 'GLOBAL');
INSERT INTO salary (emp_name, salary) VALUES ('qnteeaussy', 58000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('xookwmlsqo', '90627062', 'MGR', 'HR', 'APAC');
INSERT INTO salary (emp_name, salary) VALUES ('xookwmlsqo', 81000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('nevcsycfjt', '97200066', 'MGR', 'HR', 'SG');
INSERT INTO salary (emp_name, salary) VALUES ('nevcsycfjt', 39000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('osrngpztkx', '94856139', 'MGR', 'HR', 'HK');
INSERT INTO salary (emp_name, salary) VALUES ('osrngpztkx', 95000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('vuhybxiovl', '96498088', 'MGR', 'HR', 'EMEA');
INSERT INTO salary (emp_name, salary) VALUES ('vuhybxiovl', 43000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('ybxuheiiyn', '98281657', 'MGR', 'HR', 'LON');
INSERT INTO salary (emp_name, salary) VALUES ('ybxuheiiyn', 68000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('zpvzbkqwtm', '95115427', 'MGR', 'HR', 'PAR');
INSERT INTO salary (emp_name, salary) VALUES ('zpvzbkqwtm', 83000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('didniddcju', '92499426', 'MGR', 'HR', 'AMER');
INSERT INTO salary (emp_name, salary) VALUES ('didniddcju', 33000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('bldxzqjhgu', '99911580', 'MGR', 'HR', 'NY');
INSERT INTO salary (emp_name, salary) VALUES ('bldxzqjhgu', 85000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('mbvhjpvkcs', '95222480', 'MGR', 'HR', 'SF');
INSERT INTO salary (emp_name, salary) VALUES ('mbvhjpvkcs', 47000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('qvxziuwtjn', '91163608', 'EMP', 'HR', 'GLOBAL');
INSERT INTO salary (emp_name, salary) VALUES ('qvxziuwtjn', 44000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('aihworrqbd', '94915590', 'EMP', 'HR', 'APAC');
INSERT INTO salary (emp_name, salary) VALUES ('aihworrqbd', 53000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('cimxrqqxlx', '93409595', 'EMP', 'HR', 'SG');
INSERT INTO salary (emp_name, salary) VALUES ('cimxrqqxlx', 43000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('deipgmjvui', '92436907', 'EMP', 'HR', 'HK');
INSERT INTO salary (emp_name, salary) VALUES ('deipgmjvui', 40000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('acqlqsnmjp', '97084386', 'EMP', 'HR', 'EMEA');
INSERT INTO salary (emp_name, salary) VALUES ('acqlqsnmjp', 43000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('fretmqyhgh', '94200020', 'EMP', 'HR', 'LON');
INSERT INTO salary (emp_name, salary) VALUES ('fretmqyhgh', 59000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('ztngvsoxbu', '92458645', 'EMP', 'HR', 'PAR');
INSERT INTO salary (emp_name, salary) VALUES ('ztngvsoxbu', 52000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('kbxhlbogpq', '97668146', 'EMP', 'HR', 'AMER');
INSERT INTO salary (emp_name, salary) VALUES ('kbxhlbogpq', 83000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('uimpohhole', '98446814', 'EMP', 'HR', 'NY');
INSERT INTO salary (emp_name, salary) VALUES ('uimpohhole', 87000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('mambxfgfdi', '99248465', 'EMP', 'HR', 'SF');
INSERT INTO salary (emp_name, salary) VALUES ('mambxfgfdi', 55000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('obhomtidqw', '93442636', 'DIR', 'FIN', 'GLOBAL');
INSERT INTO salary (emp_name, salary) VALUES ('obhomtidqw', 43000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('xgyxyppuul', '97972258', 'DIR', 'FIN', 'APAC');
INSERT INTO salary (emp_name, salary) VALUES ('xgyxyppuul', 52000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('qlalsemgbl', '96754823', 'DIR', 'FIN', 'SG');
INSERT INTO salary (emp_name, salary) VALUES ('qlalsemgbl', 56000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('wgqdlnkrwr', '98291658', 'DIR', 'FIN', 'HK');
INSERT INTO salary (emp_name, salary) VALUES ('wgqdlnkrwr', 39000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('mtrrnoonhn', '97133092', 'DIR', 'FIN', 'EMEA');
INSERT INTO salary (emp_name, salary) VALUES ('mtrrnoonhn', 88000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('gplqtoetub', '97972304', 'DIR', 'FIN', 'LON');
INSERT INTO salary (emp_name, salary) VALUES ('gplqtoetub', 64000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('xpntmpwyeo', '99427863', 'DIR', 'FIN', 'PAR');
INSERT INTO salary (emp_name, salary) VALUES ('xpntmpwyeo', 54000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('qxsywgdjyu', '99500027', 'DIR', 'FIN', 'AMER');
INSERT INTO salary (emp_name, salary) VALUES ('qxsywgdjyu', 67000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('waiiryeryh', '92409748', 'DIR', 'FIN', 'NY');
INSERT INTO salary (emp_name, salary) VALUES ('waiiryeryh', 60000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('oxjydhekhj', '98095022', 'DIR', 'FIN', 'SF');
INSERT INTO salary (emp_name, salary) VALUES ('oxjydhekhj', 36000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('rivvcpxxgb', '93141700', 'MGR', 'FIN', 'GLOBAL');
INSERT INTO salary (emp_name, salary) VALUES ('rivvcpxxgb', 43000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('imsqzmnylm', '91259865', 'MGR', 'FIN', 'APAC');
INSERT INTO salary (emp_name, salary) VALUES ('imsqzmnylm', 62000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('mrzmsgcvds', '97513889', 'MGR', 'FIN', 'SG');
INSERT INTO salary (emp_name, salary) VALUES ('mrzmsgcvds', 59000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('xmjwzcjrze', '94811635', 'MGR', 'FIN', 'HK');
INSERT INTO salary (emp_name, salary) VALUES ('xmjwzcjrze', 90000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('wzmkgpvepi', '99621070', 'MGR', 'FIN', 'EMEA');
INSERT INTO salary (emp_name, salary) VALUES ('wzmkgpvepi', 92000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('ftvjyrhqvu', '97330995', 'MGR', 'FIN', 'LON');
INSERT INTO salary (emp_name, salary) VALUES ('ftvjyrhqvu', 62000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('hrwhbpikiu', '95491241', 'MGR', 'FIN', 'PAR');
INSERT INTO salary (emp_name, salary) VALUES ('hrwhbpikiu', 72000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('gbibgtgfoc', '99521814', 'MGR', 'FIN', 'AMER');
INSERT INTO salary (emp_name, salary) VALUES ('gbibgtgfoc', 63000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('fbuobjglcz', '96176024', 'MGR', 'FIN', 'NY');
INSERT INTO salary (emp_name, salary) VALUES ('fbuobjglcz', 43000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('twzlbuffcb', '97779528', 'MGR', 'FIN', 'SF');
INSERT INTO salary (emp_name, salary) VALUES ('twzlbuffcb', 48000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('jekioiyrlq', '96866907', 'EMP', 'FIN', 'GLOBAL');
INSERT INTO salary (emp_name, salary) VALUES ('jekioiyrlq', 30000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('lownlanesl', '94179058', 'EMP', 'FIN', 'APAC');
INSERT INTO salary (emp_name, salary) VALUES ('lownlanesl', 42000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('osmizslrlv', '99521903', 'EMP', 'FIN', 'SG');
INSERT INTO salary (emp_name, salary) VALUES ('osmizslrlv', 48000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('ghukvkwxov', '94620860', 'EMP', 'FIN', 'HK');
INSERT INTO salary (emp_name, salary) VALUES ('ghukvkwxov', 35000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('ndqhbmuqjg', '99973074', 'EMP', 'FIN', 'EMEA');
INSERT INTO salary (emp_name, salary) VALUES ('ndqhbmuqjg', 35000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('cpgkvqmlvx', '90607541', 'EMP', 'FIN', 'LON');
INSERT INTO salary (emp_name, salary) VALUES ('cpgkvqmlvx', 86000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('tzbqkncrtb', '97522682', 'EMP', 'FIN', 'PAR');
INSERT INTO salary (emp_name, salary) VALUES ('tzbqkncrtb', 80000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('pjhazeipxr', '98458389', 'EMP', 'FIN', 'AMER');
INSERT INTO salary (emp_name, salary) VALUES ('pjhazeipxr', 45000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('jxlfsysqpf', '99217278', 'EMP', 'FIN', 'NY');
INSERT INTO salary (emp_name, salary) VALUES ('jxlfsysqpf', 64000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('xhzpqntuum', '97514909', 'EMP', 'FIN', 'SF');
INSERT INTO salary (emp_name, salary) VALUES ('xhzpqntuum', 48000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('kuncnyhtiw', '93058772', 'DIR', 'ENG', 'GLOBAL');
INSERT INTO salary (emp_name, salary) VALUES ('kuncnyhtiw', 62000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('rmsryxvodt', '92682854', 'DIR', 'ENG', 'APAC');
INSERT INTO salary (emp_name, salary) VALUES ('rmsryxvodt', 33000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('avlzqgoxss', '93125041', 'DIR', 'ENG', 'SG');
INSERT INTO salary (emp_name, salary) VALUES ('avlzqgoxss', 47000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('porxjcttmy', '90646826', 'DIR', 'ENG', 'HK');
INSERT INTO salary (emp_name, salary) VALUES ('porxjcttmy', 68000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('blhqngqblg', '98253674', 'DIR', 'ENG', 'EMEA');
INSERT INTO salary (emp_name, salary) VALUES ('blhqngqblg', 59000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('bznrsdigtv', '90543423', 'DIR', 'ENG', 'LON');
INSERT INTO salary (emp_name, salary) VALUES ('bznrsdigtv', 63000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('tuwkkkpauk', '90343988', 'DIR', 'ENG', 'PAR');
INSERT INTO salary (emp_name, salary) VALUES ('tuwkkkpauk', 72000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('oaymgggrxm', '98673709', 'DIR', 'ENG', 'AMER');
INSERT INTO salary (emp_name, salary) VALUES ('oaymgggrxm', 84000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('pdxyvwqvve', '98719703', 'DIR', 'ENG', 'NY');
INSERT INTO salary (emp_name, salary) VALUES ('pdxyvwqvve', 75000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('pgayorwtid', '98994463', 'DIR', 'ENG', 'SF');
INSERT INTO salary (emp_name, salary) VALUES ('pgayorwtid', 30000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('duzswgvgdo', '98562602', 'MGR', 'ENG', 'GLOBAL');
INSERT INTO salary (emp_name, salary) VALUES ('duzswgvgdo', 46000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('zpzxfjqdmq', '92771967', 'MGR', 'ENG', 'APAC');
INSERT INTO salary (emp_name, salary) VALUES ('zpzxfjqdmq', 98000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('wssevwznck', '91335707', 'MGR', 'ENG', 'SG');
INSERT INTO salary (emp_name, salary) VALUES ('wssevwznck', 85000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('lufswnrdmw', '93941973', 'MGR', 'ENG', 'HK');
INSERT INTO salary (emp_name, salary) VALUES ('lufswnrdmw', 53000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('ckyaorycag', '91862764', 'MGR', 'ENG', 'EMEA');
INSERT INTO salary (emp_name, salary) VALUES ('ckyaorycag', 31000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('mdrovfrfcq', '91521788', 'MGR', 'ENG', 'LON');
INSERT INTO salary (emp_name, salary) VALUES ('mdrovfrfcq', 37000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('jwdsyoxqaq', '93680786', 'MGR', 'ENG', 'PAR');
INSERT INTO salary (emp_name, salary) VALUES ('jwdsyoxqaq', 67000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('turmocegxw', '97728838', 'MGR', 'ENG', 'AMER');
INSERT INTO salary (emp_name, salary) VALUES ('turmocegxw', 65000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('uvabychvkq', '94054341', 'MGR', 'ENG', 'NY');
INSERT INTO salary (emp_name, salary) VALUES ('uvabychvkq', 31000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('gbgdycbjtv', '96538913', 'MGR', 'ENG', 'SF');
INSERT INTO salary (emp_name, salary) VALUES ('gbgdycbjtv', 85000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('utyycybona', '94454491', 'EMP', 'ENG', 'GLOBAL');
INSERT INTO salary (emp_name, salary) VALUES ('utyycybona', 49000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('jtjvfiepwd', '99850791', 'EMP', 'ENG', 'APAC');
INSERT INTO salary (emp_name, salary) VALUES ('jtjvfiepwd', 90000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('xgrgstcrmv', '99518279', 'EMP', 'ENG', 'SG');
INSERT INTO salary (emp_name, salary) VALUES ('xgrgstcrmv', 45000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('qdrzyzduug', '91151332', 'EMP', 'ENG', 'HK');
INSERT INTO salary (emp_name, salary) VALUES ('qdrzyzduug', 61000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('bhtxoupegv', '96730338', 'EMP', 'ENG', 'EMEA');
INSERT INTO salary (emp_name, salary) VALUES ('bhtxoupegv', 59000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('hmhremfbgm', '90568161', 'EMP', 'ENG', 'LON');
INSERT INTO salary (emp_name, salary) VALUES ('hmhremfbgm', 32000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('bswctscamb', '99969485', 'EMP', 'ENG', 'PAR');
INSERT INTO salary (emp_name, salary) VALUES ('bswctscamb', 99000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('kslryyyrsh', '92397020', 'EMP', 'ENG', 'AMER');
INSERT INTO salary (emp_name, salary) VALUES ('kslryyyrsh', 97000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('berfqsjywk', '95661809', 'EMP', 'ENG', 'NY');
INSERT INTO salary (emp_name, salary) VALUES ('berfqsjywk', 65000);
INSERT INTO employees (emp_name, phone, position, dept, region) VALUES ('kntkzugeoo', '92024471', 'EMP', 'ENG', 'SF');
INSERT INTO salary (emp_name, salary) VALUES ('kntkzugeoo', 43000);

UPDATE salary SET sal_label = company.gen_sal_label(emp_name);