INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('rxxjwfrsaz', 'kdhlzdgbdummwbkilivbmnfzkfpeoq', 'U', 'FE', 'GLOBAL');
INSERT INTO project_budgets (proj_name, budget) VALUES ('rxxjwfrsaz', 65000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('mzccgiteri', 'jkrjbiuatznntudmrgdbjdvvudlqrq', 'U', 'FE', 'APAC');
INSERT INTO project_budgets (proj_name, budget) VALUES ('mzccgiteri', 47000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('kgbmwyjmoo', 'shouxujmjbdgtlyqzbngtlwfvnymfc', 'U', 'FE', 'SG');
INSERT INTO project_budgets (proj_name, budget) VALUES ('kgbmwyjmoo', 72000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('odejgnxlhc', 'ayxbsulmzczhmgsizomeasndgctprr', 'U', 'FE', 'HK');
INSERT INTO project_budgets (proj_name, budget) VALUES ('odejgnxlhc', 94000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('szthmdyjtl', 'ubopewsgwxvvabksgcfrxwrmzjrwwo', 'U', 'FE', 'EMEA');
INSERT INTO project_budgets (proj_name, budget) VALUES ('szthmdyjtl', 44000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('grhufkxfim', 'owcchqczqnjlmaeqgvnnbmhphhuwsr', 'U', 'FE', 'LON');
INSERT INTO project_budgets (proj_name, budget) VALUES ('grhufkxfim', 62000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('ccfhobidik', 'anpbbtolenlntgggbyhamjkvdcyakf', 'U', 'FE', 'PAR');
INSERT INTO project_budgets (proj_name, budget) VALUES ('ccfhobidik', 32000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('feegdkedmi', 'zueldfanxyawyfsqtlrklybgujrjhb', 'U', 'FE', 'AMER');
INSERT INTO project_budgets (proj_name, budget) VALUES ('feegdkedmi', 65000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('asmugbcrvk', 'gaypweslzyfqvbanukuvmmyzltoljj', 'U', 'FE', 'NY');
INSERT INTO project_budgets (proj_name, budget) VALUES ('asmugbcrvk', 32000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('whhrxfycld', 'uaxiirtndmajbmzjksenasmfltcbbz', 'U', 'FE', 'SF');
INSERT INTO project_budgets (proj_name, budget) VALUES ('whhrxfycld', 52000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('yajjvchvdi', 'bkpnvsepdxshzrkaqkeuvmgyzpjkmf', 'U', 'BE', 'GLOBAL');
INSERT INTO project_budgets (proj_name, budget) VALUES ('yajjvchvdi', 83000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('twatnmupes', 'empcnquneyjhifpoxxupdkmdniazup', 'U', 'BE', 'APAC');
INSERT INTO project_budgets (proj_name, budget) VALUES ('twatnmupes', 44000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('yuplzzkrsg', 'ckukieowhvvwsktmhgxvgpxrgncfom', 'U', 'BE', 'SG');
INSERT INTO project_budgets (proj_name, budget) VALUES ('yuplzzkrsg', 93000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('burwqawxes', 'azpodmyqwgjkqhxatuhglymguaghng', 'U', 'BE', 'HK');
INSERT INTO project_budgets (proj_name, budget) VALUES ('burwqawxes', 99000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('bncujyzyfv', 'zbowvhpwepucmkwdpwtcrgolpzqqbi', 'U', 'BE', 'EMEA');
INSERT INTO project_budgets (proj_name, budget) VALUES ('bncujyzyfv', 97000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('kckqurszqz', 'xiqwjaysrefvwtwvmzwnqwlornkdcl', 'U', 'BE', 'LON');
INSERT INTO project_budgets (proj_name, budget) VALUES ('kckqurszqz', 80000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('itdmnwedmb', 'vrswdvfszzklspvwncrpyzawnonfpo', 'U', 'BE', 'PAR');
INSERT INTO project_budgets (proj_name, budget) VALUES ('itdmnwedmb', 50000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('beyhxjjtcf', 'htmhlkxwfndmffmpsoymtdhtemgdvp', 'U', 'BE', 'AMER');
INSERT INTO project_budgets (proj_name, budget) VALUES ('beyhxjjtcf', 77000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('ukihjtomch', 'fognvkxzjtudsoggaincsustslqtky', 'U', 'BE', 'NY');
INSERT INTO project_budgets (proj_name, budget) VALUES ('ukihjtomch', 45000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('zdkpukstge', 'rxurrtxquhowyowbpasavvzjxfosge', 'U', 'BE', 'SF');
INSERT INTO project_budgets (proj_name, budget) VALUES ('zdkpukstge', 73000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('zkjvavdfyo', 'iotxybevnrapmkddwortamzkfowrvg', 'U', 'SEC', 'GLOBAL');
INSERT INTO project_budgets (proj_name, budget) VALUES ('zkjvavdfyo', 87000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('dcqakopqsh', 'uyrajqamkyjjqanfpugkxlqrtcnclm', 'U', 'SEC', 'APAC');
INSERT INTO project_budgets (proj_name, budget) VALUES ('dcqakopqsh', 94000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('vmqjrnvfmj', 'ngtvhoccjpehwhejqbzkqebtkgrokj', 'U', 'SEC', 'SG');
INSERT INTO project_budgets (proj_name, budget) VALUES ('vmqjrnvfmj', 55000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('uqfkgogzdh', 'nyllaeritqzojlopldovuxwzbvtvrv', 'U', 'SEC', 'HK');
INSERT INTO project_budgets (proj_name, budget) VALUES ('uqfkgogzdh', 51000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('ktlovtvrnp', 'rhaxndvrzkqzxcvxnchakznkvgxjss', 'U', 'SEC', 'EMEA');
INSERT INTO project_budgets (proj_name, budget) VALUES ('ktlovtvrnp', 90000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('ipvzxsfcuh', 'bgpmwynxmphyryvigainunblforqjc', 'U', 'SEC', 'LON');
INSERT INTO project_budgets (proj_name, budget) VALUES ('ipvzxsfcuh', 66000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('nctvgvqzmx', 'qyzapjsgbhblalisixhlzzcmzznnuv', 'U', 'SEC', 'PAR');
INSERT INTO project_budgets (proj_name, budget) VALUES ('nctvgvqzmx', 55000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('nmqbyuqhfl', 'eaykohvtkteqqgarytjgcjuouwctdv', 'U', 'SEC', 'AMER');
INSERT INTO project_budgets (proj_name, budget) VALUES ('nmqbyuqhfl', 52000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('tzgstdllqo', 'nmpeefpkvobzycbekuazihjxooxjpb', 'U', 'SEC', 'NY');
INSERT INTO project_budgets (proj_name, budget) VALUES ('tzgstdllqo', 77000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('xyvqzjimqz', 'jswfmqqnvxxvhezseamxtibhqrzjad', 'U', 'SEC', 'SF');
INSERT INTO project_budgets (proj_name, budget) VALUES ('xyvqzjimqz', 99000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('mjhigjfbna', 'zzxqgjzmprnvsffdhjozzkuyrxzegk', 'U', 'DEV', 'GLOBAL');
INSERT INTO project_budgets (proj_name, budget) VALUES ('mjhigjfbna', 92000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('bbfkwfalwy', 'nxypwtlpwxdszbggzdtdsyebukcdji', 'U', 'DEV', 'APAC');
INSERT INTO project_budgets (proj_name, budget) VALUES ('bbfkwfalwy', 50000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('hllrmkfjju', 'mpmazauqbuvwqjdvbojvanqsbjmusd', 'U', 'DEV', 'SG');
INSERT INTO project_budgets (proj_name, budget) VALUES ('hllrmkfjju', 65000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('blwdldhuca', 'gdfrotuyuamykaeblcudhdbhjraefq', 'U', 'DEV', 'HK');
INSERT INTO project_budgets (proj_name, budget) VALUES ('blwdldhuca', 54000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('ahofeikmzw', 'xngmrtkylgmmbkgcceesbjstuvzuut', 'U', 'DEV', 'EMEA');
INSERT INTO project_budgets (proj_name, budget) VALUES ('ahofeikmzw', 46000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('nfuqedgdiq', 'uhdxmpuxmxagefxhoamkmdgoakilbp', 'U', 'DEV', 'LON');
INSERT INTO project_budgets (proj_name, budget) VALUES ('nfuqedgdiq', 53000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('pimkgbbqgm', 'tonjqndcczfnwbayhbmggvqohppexl', 'U', 'DEV', 'PAR');
INSERT INTO project_budgets (proj_name, budget) VALUES ('pimkgbbqgm', 67000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('jzavvanleh', 'grwvyxaomzimbaallrnhkanyaezics', 'U', 'DEV', 'AMER');
INSERT INTO project_budgets (proj_name, budget) VALUES ('jzavvanleh', 87000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('vlwwhzqalk', 'txzxblyoebktgvbftyzdpawhywutjo', 'U', 'DEV', 'NY');
INSERT INTO project_budgets (proj_name, budget) VALUES ('vlwwhzqalk', 57000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('yhzjiwfqud', 'jxstuwnwvtjtptueweebageybuijwu', 'U', 'DEV', 'SF');
INSERT INTO project_budgets (proj_name, budget) VALUES ('yhzjiwfqud', 36000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('rmylpelhll', 'cooawcmdsudgdjnpncxwoajbwvcuws', 'C', 'FE', 'GLOBAL');
INSERT INTO project_budgets (proj_name, budget) VALUES ('rmylpelhll', 59000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('pgltjkdfme', 'qppgjbpfguamizbbpppsnmovuppiom', 'C', 'FE', 'APAC');
INSERT INTO project_budgets (proj_name, budget) VALUES ('pgltjkdfme', 68000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('lfgorlywdz', 'znsvzoovctqupunpwqvbvjnesjeenp', 'C', 'FE', 'SG');
INSERT INTO project_budgets (proj_name, budget) VALUES ('lfgorlywdz', 97000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('wgswivbcyq', 'yxxdgepsslkbyrbrsqhnmpchnvfngd', 'C', 'FE', 'HK');
INSERT INTO project_budgets (proj_name, budget) VALUES ('wgswivbcyq', 59000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('hitblesfei', 'xretmhtjiixtggymzirgtrcvhzdfdt', 'C', 'FE', 'EMEA');
INSERT INTO project_budgets (proj_name, budget) VALUES ('hitblesfei', 46000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('kiwmkjsfao', 'bljwfhsfctuevbaewvjejtfefpicjq', 'C', 'FE', 'LON');
INSERT INTO project_budgets (proj_name, budget) VALUES ('kiwmkjsfao', 54000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('fskbgpyzml', 'etnroxvaeemmtezboigrozqrtdhsyz', 'C', 'FE', 'PAR');
INSERT INTO project_budgets (proj_name, budget) VALUES ('fskbgpyzml', 69000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('thwjsfvjlt', 'uabeznzbxxljsugjpxrrebaurlbwfx', 'C', 'FE', 'AMER');
INSERT INTO project_budgets (proj_name, budget) VALUES ('thwjsfvjlt', 55000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('xhxonbiiuf', 'vcfabzlwnbvgfdrzmgrfflntqwquok', 'C', 'FE', 'NY');
INSERT INTO project_budgets (proj_name, budget) VALUES ('xhxonbiiuf', 90000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('jjjpjwwivh', 'ccwtmhitemblaypeweutzifycgyepb', 'C', 'FE', 'SF');
INSERT INTO project_budgets (proj_name, budget) VALUES ('jjjpjwwivh', 64000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('zrnctwoegw', 'fwiosouuducrwzuwqpjxsjgkwwjaay', 'C', 'BE', 'GLOBAL');
INSERT INTO project_budgets (proj_name, budget) VALUES ('zrnctwoegw', 94000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('ugcqavneyl', 'iccqqdykjnoeofxsotrkcgubhfhsrr', 'C', 'BE', 'APAC');
INSERT INTO project_budgets (proj_name, budget) VALUES ('ugcqavneyl', 38000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('ibpjxorfdg', 'xxagfsucsugqbajfuwxhlitvywrhfc', 'C', 'BE', 'SG');
INSERT INTO project_budgets (proj_name, budget) VALUES ('ibpjxorfdg', 30000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('ucgmsiejjb', 'yzqmoyyxwkdjobzzffoknvurhtbepg', 'C', 'BE', 'HK');
INSERT INTO project_budgets (proj_name, budget) VALUES ('ucgmsiejjb', 94000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('ttudobqgtg', 'fxdruskcmkgdeuzbtuhlmxrwfsnjxe', 'C', 'BE', 'EMEA');
INSERT INTO project_budgets (proj_name, budget) VALUES ('ttudobqgtg', 61000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('hjlkkarypa', 'ypnyimgfmfuikwuapgiwmjnhxyekwx', 'C', 'BE', 'LON');
INSERT INTO project_budgets (proj_name, budget) VALUES ('hjlkkarypa', 73000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('fildkobwhb', 'kjashgxnxncllxhrexeihfowilzmkf', 'C', 'BE', 'PAR');
INSERT INTO project_budgets (proj_name, budget) VALUES ('fildkobwhb', 79000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('qvgkuzgkjh', 'jjqxaimdqspitktgauyfshnowcwtft', 'C', 'BE', 'AMER');
INSERT INTO project_budgets (proj_name, budget) VALUES ('qvgkuzgkjh', 63000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('olhzptgicc', 'jqzgmocszktpdcixkubxqaontukomv', 'C', 'BE', 'NY');
INSERT INTO project_budgets (proj_name, budget) VALUES ('olhzptgicc', 66000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('busadmljou', 'jkhbznalphfvaqvoumiispfwcvzgac', 'C', 'BE', 'SF');
INSERT INTO project_budgets (proj_name, budget) VALUES ('busadmljou', 84000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('wmakjrvmuv', 'tempnknckucazrbfqgncakirnknvma', 'C', 'SEC', 'GLOBAL');
INSERT INTO project_budgets (proj_name, budget) VALUES ('wmakjrvmuv', 37000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('bqqajzzqjz', 'nybrgmpoekystqwyxevgyjymkbsvjl', 'C', 'SEC', 'APAC');
INSERT INTO project_budgets (proj_name, budget) VALUES ('bqqajzzqjz', 40000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('dhmlqtawth', 'elpmgdggzokhrlyqrktavkoxsthiuh', 'C', 'SEC', 'SG');
INSERT INTO project_budgets (proj_name, budget) VALUES ('dhmlqtawth', 86000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('uxnhcigchk', 'cjexbckjgighaxrmtctyxhwbdckiee', 'C', 'SEC', 'HK');
INSERT INTO project_budgets (proj_name, budget) VALUES ('uxnhcigchk', 62000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('fqyhokeymz', 'pgfigahesxeneuymlqbcykqdeyrebj', 'C', 'SEC', 'EMEA');
INSERT INTO project_budgets (proj_name, budget) VALUES ('fqyhokeymz', 91000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('skrxsfqche', 'muurpmajgnqtqdfzkpmsrvaciosydg', 'C', 'SEC', 'LON');
INSERT INTO project_budgets (proj_name, budget) VALUES ('skrxsfqche', 58000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('btqkxcomsk', 'xxpebyqpcbvnvznumnoqmivlhbmauc', 'C', 'SEC', 'PAR');
INSERT INTO project_budgets (proj_name, budget) VALUES ('btqkxcomsk', 61000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('pslovokdsh', 'blbrijtyhheqhaufzvxytpzaxeqcbi', 'C', 'SEC', 'AMER');
INSERT INTO project_budgets (proj_name, budget) VALUES ('pslovokdsh', 44000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('zvovsanmod', 'jeuodpvwituusmgwwybfepxpsdgsdf', 'C', 'SEC', 'NY');
INSERT INTO project_budgets (proj_name, budget) VALUES ('zvovsanmod', 79000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('bmvmdaixxk', 'zosmcykdhoseasmdxhneijjwtlvzqe', 'C', 'SEC', 'SF');
INSERT INTO project_budgets (proj_name, budget) VALUES ('bmvmdaixxk', 53000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('imjtcaqchr', 'jfphkvojkofphoomhqcqyxfknmsbns', 'C', 'DEV', 'GLOBAL');
INSERT INTO project_budgets (proj_name, budget) VALUES ('imjtcaqchr', 84000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('bfefhigyxm', 'puwsrzvcapvhzchrtefmmpjorxeash', 'C', 'DEV', 'APAC');
INSERT INTO project_budgets (proj_name, budget) VALUES ('bfefhigyxm', 68000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('wbcrkbjyaw', 'zdrlzrktpcldwhclifjflkpmabrmwu', 'C', 'DEV', 'SG');
INSERT INTO project_budgets (proj_name, budget) VALUES ('wbcrkbjyaw', 85000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('qgahmowcak', 'bcxqbdbxdygkfoedfagqwwyfhuekkh', 'C', 'DEV', 'HK');
INSERT INTO project_budgets (proj_name, budget) VALUES ('qgahmowcak', 96000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('jelzjqtssm', 'ngzvepenezhokvjwlwvpdifswpdvul', 'C', 'DEV', 'EMEA');
INSERT INTO project_budgets (proj_name, budget) VALUES ('jelzjqtssm', 74000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('yoidbgddqy', 'kuvruxhcwiyxbqwduiplleyuqezqly', 'C', 'DEV', 'LON');
INSERT INTO project_budgets (proj_name, budget) VALUES ('yoidbgddqy', 98000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('grcmmbwrrk', 'nshzhnkncuwqyleffgprwtqbnexcig', 'C', 'DEV', 'PAR');
INSERT INTO project_budgets (proj_name, budget) VALUES ('grcmmbwrrk', 54000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('otcothiotm', 'odkhfykdazodbsyilomjqxezskjzku', 'C', 'DEV', 'AMER');
INSERT INTO project_budgets (proj_name, budget) VALUES ('otcothiotm', 85000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('toudklffsc', 'rqqyixqewzlleawgefkhbiyzdgngdq', 'C', 'DEV', 'NY');
INSERT INTO project_budgets (proj_name, budget) VALUES ('toudklffsc', 61000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('cbvpxdwdpb', 'blzwajfxhuaknevcwffjhxvumdbpbt', 'C', 'DEV', 'SF');
INSERT INTO project_budgets (proj_name, budget) VALUES ('cbvpxdwdpb', 60000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('qogqcoezfz', 'jptdzefzfsmslcppyxijmqqhhpkorb', 'S', 'FE', 'GLOBAL');
INSERT INTO project_budgets (proj_name, budget) VALUES ('qogqcoezfz', 75000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('ygoftkcxjm', 'rwxklxzgxiuhkwxxtuqcykubvpjicv', 'S', 'FE', 'APAC');
INSERT INTO project_budgets (proj_name, budget) VALUES ('ygoftkcxjm', 70000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('mxnrpoonvm', 'doawmlzgaqdlgtvdixicpyusvbdmyi', 'S', 'FE', 'SG');
INSERT INTO project_budgets (proj_name, budget) VALUES ('mxnrpoonvm', 55000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('glwvnncesb', 'uqwzecfbqrojactjcolqlvdyxdkpoi', 'S', 'FE', 'HK');
INSERT INTO project_budgets (proj_name, budget) VALUES ('glwvnncesb', 64000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('eswxvopvtx', 'djeizdqeqwhsuevdkrzzszoluqrski', 'S', 'FE', 'EMEA');
INSERT INTO project_budgets (proj_name, budget) VALUES ('eswxvopvtx', 68000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('kiqsfooevi', 'qvpkjffqyodtqjkfovmyogltxsdnqg', 'S', 'FE', 'LON');
INSERT INTO project_budgets (proj_name, budget) VALUES ('kiqsfooevi', 55000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('ssgolpsmhk', 'dhijzfmdcllibmybswcypbrermemfa', 'S', 'FE', 'PAR');
INSERT INTO project_budgets (proj_name, budget) VALUES ('ssgolpsmhk', 71000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('miifcjbspg', 'rmghvkwhgciebwmdmfpkibmyegqsub', 'S', 'FE', 'AMER');
INSERT INTO project_budgets (proj_name, budget) VALUES ('miifcjbspg', 76000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('irbjkfoyil', 'budcavimhgydyximvgqrqgbniseobe', 'S', 'FE', 'NY');
INSERT INTO project_budgets (proj_name, budget) VALUES ('irbjkfoyil', 43000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('yoqhukkewk', 'lalibgbhnverrijtodzidvuudjiyui', 'S', 'FE', 'SF');
INSERT INTO project_budgets (proj_name, budget) VALUES ('yoqhukkewk', 93000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('prdqgqkiyh', 'eofurtlnmnjlukbbdobsdtgxkyvfjm', 'S', 'BE', 'GLOBAL');
INSERT INTO project_budgets (proj_name, budget) VALUES ('prdqgqkiyh', 98000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('wzzkkqvaxi', 'mgsuzykxjhhzqerncrejywjanepylq', 'S', 'BE', 'APAC');
INSERT INTO project_budgets (proj_name, budget) VALUES ('wzzkkqvaxi', 82000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('rskqfzntvb', 'bunrxrhnuazqieqikwodrevotyisaa', 'S', 'BE', 'SG');
INSERT INTO project_budgets (proj_name, budget) VALUES ('rskqfzntvb', 50000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('iinvyrppua', 'ltlqcmdhynhtqxjhziackwmohjcsff', 'S', 'BE', 'HK');
INSERT INTO project_budgets (proj_name, budget) VALUES ('iinvyrppua', 64000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('ztvmmjmour', 'lsmsesgpvbbqmbdzhkxunppxwkvyqf', 'S', 'BE', 'EMEA');
INSERT INTO project_budgets (proj_name, budget) VALUES ('ztvmmjmour', 86000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('anxbnvqtol', 'wnpqhoxqswlgiaokwckhsbubabpxrm', 'S', 'BE', 'LON');
INSERT INTO project_budgets (proj_name, budget) VALUES ('anxbnvqtol', 34000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('bavtzgvnuh', 'lpnunqltctfsdkxferlrrmzehbxvgc', 'S', 'BE', 'PAR');
INSERT INTO project_budgets (proj_name, budget) VALUES ('bavtzgvnuh', 85000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('spuulnyrdk', 'faygpvpbmcfdtirabwwnhubjkhkuxq', 'S', 'BE', 'AMER');
INSERT INTO project_budgets (proj_name, budget) VALUES ('spuulnyrdk', 42000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('xgeqetvzlj', 'kroelcaydwksvgmxmrmgbarjymjvdr', 'S', 'BE', 'NY');
INSERT INTO project_budgets (proj_name, budget) VALUES ('xgeqetvzlj', 54000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('ktuhpjlpuq', 'gxompzjzwpsfmrnactjskyevmgffuy', 'S', 'BE', 'SF');
INSERT INTO project_budgets (proj_name, budget) VALUES ('ktuhpjlpuq', 30000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('pdbmsmjitt', 'iayhjxcgowgbvyotjcfqzlyfymxdga', 'S', 'SEC', 'GLOBAL');
INSERT INTO project_budgets (proj_name, budget) VALUES ('pdbmsmjitt', 59000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('smsclbtvlh', 'szxcfhamppixxlnzyctnpitpvajlrv', 'S', 'SEC', 'APAC');
INSERT INTO project_budgets (proj_name, budget) VALUES ('smsclbtvlh', 34000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('qpagvhadzi', 'gilllscgdtnxyniemlbmdfmmybgtov', 'S', 'SEC', 'SG');
INSERT INTO project_budgets (proj_name, budget) VALUES ('qpagvhadzi', 87000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('ickbzdlrof', 'whxhzjhxfcbpcfqohfncfynkqzvgoa', 'S', 'SEC', 'HK');
INSERT INTO project_budgets (proj_name, budget) VALUES ('ickbzdlrof', 82000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('ytsmtjylpa', 'pweowdnhedfsveekqbezztoguqjpzg', 'S', 'SEC', 'EMEA');
INSERT INTO project_budgets (proj_name, budget) VALUES ('ytsmtjylpa', 65000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('knjbbmgvqb', 'ihtggiytnrgnwiptxkuguoyaipvjwm', 'S', 'SEC', 'LON');
INSERT INTO project_budgets (proj_name, budget) VALUES ('knjbbmgvqb', 66000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('xiwipasdvr', 'waqyejquabtvrzfxdiglzhglqvhjay', 'S', 'SEC', 'PAR');
INSERT INTO project_budgets (proj_name, budget) VALUES ('xiwipasdvr', 45000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('mzopvdijpi', 'rvuyxqbwlwubtgesjyutdfoycydsts', 'S', 'SEC', 'AMER');
INSERT INTO project_budgets (proj_name, budget) VALUES ('mzopvdijpi', 52000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('sreqhctngv', 'nnqqtqantutrwucpnhwtpyzpfmgeix', 'S', 'SEC', 'NY');
INSERT INTO project_budgets (proj_name, budget) VALUES ('sreqhctngv', 90000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('blbfgirtyd', 'qsybyachvuxjkybugzdqdluoyuhozk', 'S', 'SEC', 'SF');
INSERT INTO project_budgets (proj_name, budget) VALUES ('blbfgirtyd', 35000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('vqjutxibin', 'ijhrogskkhbjuhskiwqnlmanspdeih', 'S', 'DEV', 'GLOBAL');
INSERT INTO project_budgets (proj_name, budget) VALUES ('vqjutxibin', 43000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('diaxvhirrf', 'tobqfghatifizvdcdcvoqzefybrycv', 'S', 'DEV', 'APAC');
INSERT INTO project_budgets (proj_name, budget) VALUES ('diaxvhirrf', 67000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('pyjcekmhfw', 'hbmsmxpstpkxcffpfhdixlsdwhkkfu', 'S', 'DEV', 'SG');
INSERT INTO project_budgets (proj_name, budget) VALUES ('pyjcekmhfw', 67000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('zijfvzyeaf', 'ethjkozpbxokhloymtqypzdzetikqt', 'S', 'DEV', 'HK');
INSERT INTO project_budgets (proj_name, budget) VALUES ('zijfvzyeaf', 90000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('zcinjbaujg', 'pbddrbeodxwxlavpkelxbxqwiohliz', 'S', 'DEV', 'EMEA');
INSERT INTO project_budgets (proj_name, budget) VALUES ('zcinjbaujg', 51000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('zsyhdowzvl', 'pqotzhazshgceiuygaumneommlnhym', 'S', 'DEV', 'LON');
INSERT INTO project_budgets (proj_name, budget) VALUES ('zsyhdowzvl', 71000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('alkphmcwbb', 'frmpzriaxrjdcschlgrhjnogrxubpa', 'S', 'DEV', 'PAR');
INSERT INTO project_budgets (proj_name, budget) VALUES ('alkphmcwbb', 58000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('kwqgyvjqtu', 'uffllashmtaxrnaozmkcpqgkzjqihu', 'S', 'DEV', 'AMER');
INSERT INTO project_budgets (proj_name, budget) VALUES ('kwqgyvjqtu', 43000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('ottzvlworj', 'eqrhjewonkxdpmmboejimfdjnzpgfw', 'S', 'DEV', 'NY');
INSERT INTO project_budgets (proj_name, budget) VALUES ('ottzvlworj', 50000);
INSERT INTO projects (proj_name, description, classification, eng_type, region) VALUES ('yocrnzpefj', 'vficvajblrtmblhpdrkpjlwpwarahi', 'S', 'DEV', 'SF');
INSERT INTO project_budgets (proj_name, budget) VALUES ('yocrnzpefj', 83000);
